### PR TITLE
Remove diagnostic id from message

### PR DESCRIPTION
**Pull request by henryju**
Relates to https://github.com/OmniSharp/omnisharp-roslyn/issues/1622

In VSCode, the diagnostic id should better be passed in the `code` attribute. Having it also in the message lead to duplication in the UI.

### CODE REVIEW

**Comment by filipw** [comment]
I have no problem with this change however there are other consumers of these APIs than just VS Code, and it might be that removing the ID from the message could "break" them.

@razzmatazz @nickspoons is this change OK to you - you'd need to pick up the diagnostic ID from a dedicated property as it will no longer be in the message text

also, are you using https://github.com/OmniSharp/csharp-language-server-protocol?

**Comment by henryju** [comment]
> also, are you using https://github.com/OmniSharp/csharp-language-server-protocol?

If the question was for me, then no, I'm not using it. We are currently only targeting VSCode integration, and from what I saw, the VSCode C# extension are calling directly the omnisharp server, without relying on the LSP.

**Comment by nickspoons** [comment]
@filipw thanks for checking. This no problem from OmniSharp-vim's side, we use the `Id` property already. If users decide they miss seeing the Id in the message, we can just add it on our end.

I also am unsure who the LSP question was to - we don't use it. We use the stdio version without LSP, and still also use the HTTP version for older clients that can't use stdio.

**Comment by nickspoons** [comment]
Not necessarily at the same time - it just has to be merged _after_ the VSCode PR. This issue is just removing the code from the message - it is already available in the `Id` property so the VSCode PR can go first.

**Comment by filipw** [comment]
sorry I meant "this needs to be merged too" - English is my 3rd language

**Comment by razzmatazz** [comment]
Sorry, I cannot check the code for the moment as I’m on vacation. Will update the code if it actually does use the Id field after your update.

However, no, omnisharp-emacs does not use lsp.

—Saulius Menkevičius

**Comment by david-driscoll** [comment]
The change seems reasonable to me.  LSP supports the code as well, so that should map through.  https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#Diagnostic

**Pull request merged**
