### PR TITLE
pinned gitversion

### PR DESCRIPTION
**Pull request by david-driscoll**
cc @rchande @akshita31 @mholo65 @gep13

### CODE REVIEW

**Comment by rchande** [comment]
@david-driscoll How are you planning to validate that this worked?

**Comment by DustinCampbell** [comment]
Does this fix https://github.com/OmniSharp/omnisharp-roslyn/issues/1202?

**Comment by mholo65** [comment]
@rchande you can see [here](https://ci.appveyor.com/project/david-driscoll/omnisharp-roslyn/build/1.32.3-PullRequest1278.31.build.3664?fullLog=true#L113) that it works.

**Comment by akshita31** [comment]
@DustinCampbell I tried today with the latest master and #1202 isn't fixed by this change.

**Comment by gep13** [comment]
@akshita31 can you please confirm, by looking in the tools folder, what version of GitVersion is installed in that folder?  You should be able to right click on the exe, and select Properties, then find the version number in the details tab.

**Pull request merged**
