### PR TITLE
Escape markdown to fix plaintext returns.

### LINKED ISSUE #1556: [LSP] Server is returning plaintext inside MarkedString
I'm seeing this a lot with hover text.  When I hover over a Linq Where clause, the server returns this:

```JSON
{
    "contents": [
        "IEnumerable<KeyValuePair<int, string>> IEnumerable<KeyValuePair<int, string>>.Where<KeyValuePair<int, string>>(Func<KeyValuePair<int, string>, bool> predicate)",
        "Filters a sequence of values based on a predicate.\nsource: An System.Collections.Generic.IEnumerable`1 to filter.\npredicate: A function to test each element for a condition.The type of the elements of source .\nReturns: An System.Collections.Generic.IEnumerable`1 that contains elements from the input sequence that satisfy the condition.\nSystem.ArgumentNullException: source or predicate is null."
    ]
}
```

As you can see, the contents includes ``System.Collections.Generic.IEnumerable`1`` many times.  Back quotes are markdown that inserts inline code blocks.  This causes that text to be rendered like this:

Filters a sequence of values based on a predicate.
source: An System.Collections.Generic.IEnumerable`1 to filter.
predicate: A function to test each element for a condition.The type of the elements of source .
Returns: An System.Collections.Generic.IEnumerable`1 that contains elements from the input sequence that satisfy the condition.
System.ArgumentNullException: source or predicate is null.

The returned text should escape the back quote: ``System.Collections.Generic.IEnumerable\`1``

source: An System.Collections.Generic.IEnumerable\`1 to filter.
predicate: A function to test each element for a condition.The type of the elements of source .
Returns: An System.Collections.Generic.IEnumerable\`1 that contains elements from the input sequence that satisfy the condition.
System.ArgumentNullException: source or predicate is null.

### PR DESCRIPTION
**Pull request by LoneBoco**
Fixes #1556.  Omnisharp is returning plaintext and assigning to MarkedString, which, according to the LSP spec, is a markdown formatted string.  Add a function to escape the text to prevent parsing errors.

### CODE REVIEW

**Comment by LoneBoco** [comment]
I'm not sure if you would be happy with using Regex to fix this, but it should handle all the possible escaped Markdown characters as shown [in the Markdown guide](https://www.markdownguide.org/basic-syntax/#escaping-characters).

**Comment by david-driscoll** [comment]
Just making sure the errors were transient with the build.  Thanks @LoneBoco for the contribution!

**Pull request merged**
