### PR TITLE
Modified OmniSharp to work as it used to to avoid breaking emacs and vim

### PR DESCRIPTION
**Pull request by david-driscoll**

### CODE REVIEW

**Comment by dgalizzi** [comment]
Tried this by running the Omnisharp.cmd on windows and it solves #356 . But tried the same (Omnisharp.sh) on linux and didn't (doesn't throw the exception but I'm not getting any response).

**Comment by dgalizzi** [comment]
Got it to work on linux! I added -s [path to folder] and worked. Still I didn't have to do that in Windows or with omnisharp-server.

**Comment by david-driscoll** [comment]
Good to hear... I'll see if I can make some changes so that it won't break vim or emacs

**Comment by david-driscoll** [comment]
rather doesn't break them, without any modifications to those plugins

**Comment by david-driscoll** [comment]
@dgalizzi If you get a chance to test out this branch again, instead this time, hopefully you shouldn't have to make any changes to the emacs config to make it work.

**Comment by davidfowl** [comment]
?

**Pull request merged**
