### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by troydai**

### CODE REVIEW

**Comment by DustinCampbell** [comment]
Change looks good, though it failed to get some of the packages.

**Comment by david-driscoll** [comment]
Lgtm once ci passed 😃

**Comment by troydai** [comment]
investigating the build errors. may be some packages are still being shifted.

**Comment by DustinCampbell** [comment]
fingers crossed!

**Comment by troydai** [comment]
My mistake, duplicate feed names causes one feed ignored.

**Comment by troydai** [comment]
fixing a new build error now. some breaking api change in hosting.

**Comment by troydai** [comment]
it was fixed on dev branch. vscode branch is actually behind.

**Comment by DustinCampbell** [comment]
Cool!

**Comment by troydai** [comment]
oh, no. the test will fail because a mismatch in dotnet-test-xunit on aspnetcirelease and cli. working on a solution.

**Comment by troydai** [comment]
@hal-ler something's wrong with cake script build on mac environment: 
```
Successfully installed 'Cake 0.11.0' to /Users/travis/build/OmniSharp/omnisharp-roslyn/.tools
Analyzing build script...
Processing build script...
Installing addins...
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Comment by hal-ler** [comment]
@david-driscoll We saw similar behavior earlier as NuGet getting into an infinite loop on OSX. It was fixed, by pinning the NuGet binary to v3.3.0. Did something else also change, like the Mono version?

**Comment by troydai** [comment]
Can we I merge this without Mac testing?

**Comment by troydai** [comment]
I'll merge to the vscode branch anyway. we should keep looking into the mac build environment.

**Comment by hal-ler** [comment]
Oh you were behind dev? Then pull in https://github.com/OmniSharp/omnisharp-roslyn/commit/bba128a507ca4587cf6c0b411ce3d0fe528daa3a. That fixes the issue.

**Comment by DustinCampbell** [comment]
Yeah, it looks like that change isn't there. I'll cherry-pick it.

**Pull request merged**
