### PR TITLE
Use --zero-based-indices argument in Stdio and Http hosts

### PR DESCRIPTION
**Pull request by daviwil**
This change fixes an issue where the --zero-based-indices command
line argument was not being passed along to Configuration.ZeroBasedIndices
so that location/range serialization uses zero-based indices. This
fix wires up the argument to configure the serializer correctly.

### CODE REVIEW

**Comment by daviwil** [comment]
Man, TravisCI is super slow today, looks like the build jobs timed out while the tests were running.

**Comment by filipw** [comment]
public static field 🙄 🤐 😄

**Comment by DustinCampbell** [comment]
@daviwil : yeah, the OSX jobs get super-slow during US business hours.

**Comment by DustinCampbell** [comment]
I'm going to go ahead and force merge this. It doesn't *actually* have conflicts with master

**Comment by daviwil** [comment]
Thanks a lot Dustin!

**Pull request merged**
