### PR TITLE
Detect when files move to empty directories

### PR DESCRIPTION
**Pull request by rchande**
Augment the IFileSystemWatcher to allow watching a directory
recursively. This enables OmniSharp to watch a project's entire
directory tree (as oppposed to the specific subdirectories that contain
documents)

### CODE REVIEW

**Comment by SirIntruder** [comment]
Glad to see this issue finally getting on the chopping block! Yet, I have questions 😆 

1. Wouldn't this result in double trigger of "OnDocumentChanged" when doing stuff in existing directories?

2. Seems there is an arbitrary limitation of only one "WatchRecursively" listener being able to be triggered per event?

Looking at this, I wonder can't MSBuildProjectmanager just subscribe to all "*.cs" on start instead of doing anything per directory? BufferManager will put new files into correct projects, and others will be forwarded to the misc project. If anything, it should make dispatching events in ManualSystemWatcher cheaper, as it would replace 100s of hooks with just one (note that ManualSystemWatcher is not a real system file watcher, it just re-distributes upstream events coming from /fileChanged endpoint. I was confused by this at first)

**Comment by rchande** [comment]
@SirIntruder 

> I wonder can't MSBuildProjectmanager just subscribe to all "*.cs" on start instead of doing anything per directory?

Interesting idea. Let's see what the tests have to say about that...

**Comment by rchande** [comment]
And of course, if that's a good solution, maybe we can get rid of the "FileSystemWatcher" concept altogether, since as you say, it's more of an abstraction for controlling what events from the "real" file system get handled.

**Comment by rchande** [comment]
@filipw care to review?

**Pull request merged**
