### PR TITLE
Making project collection case-insensitive.

### PR DESCRIPTION
**Pull request by carl-tanner**
I'm having problems with large projects (100s of projects) because the project references in msbuild projects don't always match the same case as paths in the solution (or file paths on disk).  Believe this should be case insensitive.

### CODE REVIEW

**Comment by david-driscoll** [comment]
I can't see an issue with the change.  @troydai @DustinCampbell any input before we merge?

**Comment by DustinCampbell** [comment]
:+1: we've had this same bug in Visual Studio as well. :smile:

**Comment by troydai** [comment]
go ahead. better to have a test though.

**Comment by carl-tanner** [comment]
Fair enough.  I added a unit test.

**Comment by troydai** [comment]
@carl-tanner this looks good to me. Please rebase on the latest dev. Once the CI passes, I can help merge this PR.

**Comment by carl-tanner** [comment]
Not sure what happened in the tests.  I took a look at the log and it looks like it has something to do with some mono internal error.  My changes passed before.  I think it's unlikely it failed due to my changes.  Is there any way to re-kick the validations?

**Comment by troydai** [comment]
rekick the build. it's not you. it's a mono error.

**Comment by carl-tanner** [comment]
Looks like stuff failed again.  Is there a problem with mac xunit?  The error has been at the same point each run:

xUnit.net Console Runner (32-bit .NET 4.0.30319.17020)
  Discovering: OmniSharp.Stdio.Tests
  Discovered:  OmniSharp.Stdio.Tests
  Starting:    OmniSharp.Stdio.Tests
  Finished:    OmniSharp.Stdio.Tests
* Assertion: should not be reached at ./sgen-scan-object.h:101

It looks like the failure happens after the tests run.

**Comment by carl-tanner** [comment]
Yay, Build passed.  Please merge in to dev.

**Comment by troydai** [comment]
Merged. Thanks for the contribution @carl-tanner.

**Pull request merged**
