### PR TITLE
Fix break due to dotnet API change

### PR DESCRIPTION
**Pull request by panopticoncentral**

### CODE REVIEW

**Comment by troydai** [comment]
Yeah. It's good. But can you make sure the CI passes?

**Comment by troydai** [comment]
Looks like CI timeout. I restarted the build. Code change is ok. You can merge whenever CI passed.

Thank you.

**Comment by panopticoncentral** [comment]
retest continuous-integration/travis-ci/pr please
// Previous failure: https://travis-ci.org/OmniSharp/omnisharp-roslyn/builds/111373187
// Retest reason:

**Comment by troydai** [comment]
@panopticoncentral I'll close this since I fixed the build break in my latest commit:
https://github.com/OmniSharp/omnisharp-roslyn/commit/d92d6b5e85cbdd67452bea6ef73e2d76efe32058

Thanks for looking into it.

**Pull request closed without merging**
