### PR TITLE
Update Mono to 6.8.0

### PR DESCRIPTION
**Pull request by JoeRobich**
Mono 6.6.0 added a dependency on libintl that ships in the Mono pkg (https://github.com/mono/mono/pull/18531). This dependency has been removed from later builds of 6.8.0.

Tested locally with 6.8.0.96 and saw failures. The stable MacOS release of 6.8.0.104 contains the fix. Linux builds use 6.8.0.96 as that is the released stable build.

Resolves https://github.com/OmniSharp/omnisharp-roslyn/issues/1693
Resolves https://github.com/OmniSharp/omnisharp-vscode/issues/3545

### CODE REVIEW

**Comment by filipw** [comment]
during the .NET Core 3.0 debacle with msbuild 16.3 the build script was updated to copy MSBuild from global mono at the build agent, instead of these zips. probably time to revert this 😁

**Comment by JoeRobich** [comment]
> probably time to revert this

You mean rely purely on the MSBuild zip files?

**Comment by filipw** [comment]
I am talking about this change https://github.com/OmniSharp/omnisharp-roslyn/pull/1612

would you mind reverting it as part of this PR?

otherwise we have older MSBuild in the released packages...

**Comment by JoeRobich** [comment]
Ah, gotcha. Sure thing.

**Comment by filipw** [comment]
the alternative is to remove them from the JSON completely as they are not used at the moment and update build agents to 6.8.0 too so that it's in line with the bundled runtime when it comes to MSBuild

**Comment by filipw** [comment]
I somehow don't have access to that blob storage and when we needed to urgently update to MSBuild 16.3 due to the breaking changes in .NET SDK, and Ravi was unreachable, the best and quickest idea I had was to copy from the global Mono at build time instead 😅 that's the reason behind that change in the first place, in case you were wondering... 

(sorry for slow responses, typing on mobile)

**Comment by JoeRobich** [comment]
@filipw I think building it from the build script is probably the way to go. It looks like the build script was already augmenting the msbuild zips anyways,

**Comment by filipw** [comment]
OK makes sense to me. maybe let's just align the versions here https://github.com/OmniSharp/omnisharp-roslyn/blob/master/azure-pipelines.yml#L59 and https://github.com/OmniSharp/omnisharp-roslyn/blob/master/azure-pipelines.yml#L93 with the embedded runtime ones

**Comment by JoeRobich** [comment]
In light of the way the Linux and MacOS legs failed. We may want to update this to the 6.8.0.105 version that just dropped.

**Comment by ifuseandprint** [comment]
Duplicate of #

**Pull request merged**
