### PR TITLE
Solve issue #1113.

### PR DESCRIPTION
**Pull request by LoneBoco**
Send cancellation token when the server shuts down so we terminate the process.

### CODE REVIEW

**Comment by rchande** [comment]
@david-driscoll Does this look right to you?

**Comment by mholo65** [comment]
I’d say we should look at updating LSP libs to latest instead. @david-driscoll, this is fixed there, right?

**Comment by mholo65** [comment]
That said, I might have some time updating that in the end of this week.

**Comment by LoneBoco** [comment]
I took a look at OmniSharp.Extensions.LanguageServer version 0.10.0.  I couldn't get it to work correctly because there has been a ton of changes since the 0.8.0 version I use in my local repository, but this would still be a problem with the latest version.

The issue is here:
https://github.com/OmniSharp/omnisharp-roslyn/blob/0496b7e914b70f18180d9c63b16eac7febc62708/src/OmniSharp.Stdio.Driver/Program.cs#L35-L43

OmniSharp.exe waits on the cancellation token.  The only things that trigger this cancellation token is closing the console or waiting for the host process to terminate.  If the host process sends an Exit request, the server will shut down, but the cancellation token for OmniSharp.exe will never get triggered, so the .exe keeps running.

If you want to use version 0.10.0, you have to do something like:
```C#
_server.Exit.Subscribe(_cancellationTokenSource.Token);
```

I think that would work.  I never tested it though as I couldn't get 0.10.0 to work.

**Comment by rchande** [comment]
@mholo65 @david-driscoll I haven't been following along with LSP very much so I'm going to leave it to you to handle this PR.

**Comment by filipw** [comment]
👍

**Pull request merged**
