### PR TITLE
Fixed a regression that broke FindSymbols for CSX

### PR DESCRIPTION
**Pull request by filipw**
This PR fixes a regression introduced in https://github.com/OmniSharp/omnisharp-roslyn/pull/1282 that broke symbol search for CSX.
I also enabled the FindSymbolsFacts to specifically run twice - once for both regular C# and once for CSX to prevent this in the future (we have same pattern on most tests, but it wasn't there on this one though).

This is quite critical so it would be great to merge this ASAP.

### CODE REVIEW

**Comment by mholo65** [comment]
I remember mentioning this in the original PR here https://github.com/OmniSharp/omnisharp-roslyn/pull/1282#discussion_r215375984

**Comment by filipw** [comment]
ah I was on holidays then so it slipped past me 😄

**Comment by rchande** [comment]
@filipw re: shipping this--A big focus for the C# extension in 17.0 has been working with the Asp.NET team to ship an initial Razor experience in the extension. This has involved a lot of validation based on the 1.32.6 release of OmniSharp. Since 1.32.6, there have been other changes unrelated to this one, so we'd probably need to redo some of our validation if we inserted 1.32.7 to the extension. We first shipped the CSX find symbols regression in 1.16.0 in September, so it has been this way for some time. I would prefer to merge your fix and recommend that users who need it set the "omnisharp.version" option to "latest". We can then insert 1.32.7 into 17.1 and include it in betas. Thoughts?

**Comment by filipw** [comment]
thanks, that's OK, let's do it that way

After 1.17.0 ships, would be great if you could publish the 1.17.1-beta1 fairly quickly though, so that there is a concrete extension build that can be installed as a workaround. 
The "latest" way works in the immediate term (as soon as this PR is merged) but longer term is a bit invasive, plus we had broken builds on master before 😀

**Comment by filipw** [comment]
I will merge it then 👍

**Pull request merged**
