### PR TITLE
Strong-name sign OmniSharp assemblies

### PR DESCRIPTION
**Pull request by 333fred**
In order to use https://github.com/dotnet/roslyn/pull/52907, we're going to need to strong-name sign the OmniSharp assemblies. This does just that.

### CODE REVIEW

**Comment by 333fred** [comment]
@filipw @david-driscoll please take a look.

**Review by filipw — APPROVED** [review]
LGTM thank you

**Review by bjorkstromm — APPROVED** [review]
LGTM!

**Comment by davevans** [comment]
Should I expect Omnisharp.exe to be signed at this point? I have 1.37.0 and there is no digital signature on the exe 
image

**Comment by 333fred** [comment]
Strong name signing does not refer to that type of digital signature. And yes, Omnisharp has been shipping strongname signed binaries since 1.37.9.

**Pull request merged**
