### PR TITLE
added builds for additional runtimes, linux is now an alias for ubuntu

### PR DESCRIPTION
**Pull request by david-driscoll**

### CODE REVIEW

**Comment by david-driscoll** [comment]
cc @DustinCampbell this may require a change to how vscode looks up what OS it's running on, you'll have to infer the distro based on similar logic that `cli` / `coreclr` use.

**Comment by hal-ler** [comment]
What will be the logic for populating the the runtime list in the script with the other linux distros? Everything done on Travis/Ubuntu and otherwise stick to default runtime?

**Comment by DustinCampbell** [comment]
Thanks @david-driscoll -- it will change VS Code slightly, but it's a small change and makes things better. At the moment, VS Code will grab the "linux" distro, which fails to launch on RHEL/CentOS.

**Comment by david-driscoll** [comment]
@hal-ler my hope (that needs to be tested) is that even though it was built on `trusty` (travis) that they will run correctly on `RHEL` / `CentOS` because of the different runtime provided.  I'm assuming the binary format of `OmniSharp` doesn't change.

If that isn't the case... then I guess I have to setup some sort of Azure VMs to shuffle the build bits too.

**Comment by hal-ler** [comment]
I think that it should work. Just make sure to also populate the list with the new runtimes (PopulateRuntimes in build.cake).

**Pull request merged**
