### PR TITLE
Update changelog with latest changes for 1.28

### PR DESCRIPTION
**Pull request by DustinCampbell**
Here's an update to the CHANGELOG for OmniSharp 1.28. Also, this is an official heads-up/reminder to include a changelog update when making PRs. :smile:

cc @mholo65

### CODE REVIEW

**Comment by filipw** [comment]
I think both https://github.com/OmniSharp/omnisharp-roslyn/pull/1056 and https://github.com/OmniSharp/omnisharp-roslyn/pull/1054 should still be merged before 1.28 release

**Comment by DustinCampbell** [comment]
Agreed! Maybe changelog updates could be added to those PRs?

**Comment by DustinCampbell** [comment]
Since this is a markdown-only change, I'm going to go ahead and merge without waiting on the Mac build.

**Comment by mholo65** [comment]
@DustinCampbell if you don't mind, we'd be really happy to get #1057 merged for 1.28 as well. I'll push the release bits for `Cake.Scripting` and friends to NuGet tonight and update that PR.

**Comment by DustinCampbell** [comment]
@mholo65 : We'll wait for you to be ready before releasing 1.28.

**Pull request merged**
