### PR TITLE
Lsp init fix

### PR DESCRIPTION
**Pull request by yatli**
Some background:

https://github.com/coc-extensions/coc-omnisharp/issues/33

https://github.com/coc-extensions/coc-omnisharp/issues/35

https://github.com/OmniSharp/omnisharp-roslyn/issues/1742

https://github.com/OmniSharp/omnisharp-roslyn/issues/1515

https://github.com/OmniSharp/omnisharp-roslyn/issues/1083

--------

In short, there's race condition between (workspace initialization + project reference adding) and (client requests coming in at a random point of time).

This PR blocks incoming LSP requests until the initial project system processing is completed. Should help us to get rid of a bunch of issues.

### CODE REVIEW

**Comment by david-driscoll** [comment]
@yatli Sorry for the delay.

I got looking into this.

I think I'm okay with the addition to the project system @filipw or @JoeRobich if you could comment if you have any issues with the functionality (or 🚲 🏠 ).

The plumbing through the initialized handler looks like a code smell to me.  

There is a better solution but because my documentation on the csharp-lsp library is limited, I'm sure you just didn't know about it.
I've made a single commit to this branch: https://github.com/OmniSharp/omnisharp-roslyn/tree/dd-lsp-init-proposed-fix with the changes to use the `OnInitialized` even to wait for the workspaces to be started.  This event fires just before the server returns the initialize response to the client.

**Comment by david-driscoll** [comment]
If you can give it a test spin for me to make sure it solves _your_ issue, then we can go with that.

**Comment by yatli** [comment]
Thanks @david-driscoll !

Will test it out and report back.

**Comment by yatli** [comment]
Can confirm it solves the initial loading problem.

**Review by filipw — APPROVED** [review]
looks good to me

**Comment by yatli** [comment]
@david-driscoll shall I merge your branch?

**Comment by david-driscoll** [comment]
Thanks @yatli !

**Pull request merged**
