### PR TITLE
Fix build break and update dependencies

### PR DESCRIPTION
**Pull request by troydai**

### CODE REVIEW

**Comment by troydai** [comment]
Waiting for the CI.

**Comment by david-driscoll** [comment]
:tada:

**Comment by troydai** [comment]
Investigating the restore failure. Seems to relate new DNX. I may replace the dnu restore with dotnet restore. Stay tuned.

**Comment by david-driscoll** [comment]
Nice, is it ready to go you think?

I'm currently building locally and will test with atom for a bit.

**Comment by david-driscoll** [comment]
`PackagesRestoreTool` seems to crash the server now.

Also the scripts need their dnx rc2 version updated (I can do that later)

**Comment by troydai** [comment]
I think it's good enough to unblock the build. But yeah, DNX is going to be removed very soon.

**Comment by david-driscoll** [comment]
Yeah, lets merge for now, still worried it's going to break in 2 days again.

**Comment by troydai** [comment]
You don't have to way for 2 days. It's already broken now :P. The 16420 build is missing. I upgrade them to 16425. I'll wait for the CI pass.

**Comment by troydai** [comment]
CI passed. Let's go.

**Pull request merged**
