### PR TITLE
Do #load traversal recursively in scriptcs subsystem, #512

### PR DESCRIPTION
**Pull request by gaborv**
This is a refactoring and rewrite of the initialization logic in the ScriptCs subsytem.
The aims are the following:

1. Support .csx files in all subdirectories not just root
2. Do not crash on multiple `#load# references in scripts
3. Follow `#load` references recursively and map them to proper project references
4. Do not break anything that worked before.

### CODE REVIEW

**Comment by david-driscoll** [comment]
I'm not deeply invested in the ScriptCS stuff, but the changes look good to me.  @filipw what are your thoughts?

**Comment by filipw** [comment]
Yeah I agree, great PR.
:shipit:

**Comment by david-driscoll** [comment]
:+1:

**Comment by david-driscoll** [comment]
Thanks for the pull request @gaborv ! :tada:

**Pull request merged**
