### PR TITLE
comment out aspnetcore50

### PR DESCRIPTION
**Pull request by jrieken**
We have a problem with the ```Microsoft.Framework.FileSystemGlobbing```-dependency: https://github.com/OmniSharp/omnisharp-roslyn/pull/158#discussion_r28417355

### CODE REVIEW

**Comment by nosami** [comment]
From the build log

```
/home/travis/build/OmniSharp/omnisharp-roslyn/src/OmniSharp/AspNet5/AspNet5ProjectSystem.cs(16,27): error CS0234: The type or namespace name 'FileSystemGlobbing' does not exist in the namespace 'Microsoft.Framework' (are you missing an assembly reference?)
/home/travis/build/OmniSharp/omnisharp-roslyn/src/OmniSharp/AspNet5/AspNet5ProjectSystem.cs(531,35): error CS0246: The type or namespace name 'Matcher' could not be found (are you missing a using directive or an assembly reference?)
```

This has highlighted that our CI process is broken. We have a [hack](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/build.sh#L20) in our build script because `kpm bundle` didn't return the correct error code. @davidfowl Is that fixed yet?

We should be grepping for "Build Failed" and inverting. In the log we have one "Build Failed" message and one "Build Succeeded"

**Comment by davidfowl** [comment]
Ugggghh, this needs to be fixed, not commented out. I'll look into it.

**Comment by jrieken** [comment]
yeah - its not merged but I needed that branch

**Comment by davidfowl** [comment]
So 2 bugs, we need to grep for build failed

**Comment by nosami** [comment]
fixed by #168

**Pull request closed without merging**
