### PR TITLE
Added missing space

### PR DESCRIPTION
**Pull request by michaldudak**
Inspired by @adamralph DevDay talk

### CODE REVIEW

**Comment by adamralph** [comment]
:shipit:

**Comment by david-driscoll** [comment]
but you failed appveyor!  Clearly that space was the issue :tada:

**Comment by david-driscoll** [comment]
(okay, I'm kidding) :laughing:

**Comment by michaldudak** [comment]
Yay! @adamralph - thanks for the inspiration. Once I saw this "issue" on the video I knew I had to correct it ;). I'll look for something bigger next time.

**Comment by adamralph** [comment]
@michaldudak :+1: glad to hear it.

BTW - I would have fixed it too :wink:

**Comment by david-driscoll** [comment]
`ctrl-k, ctrl-d` :ice_cream:

**Comment by filipw** [comment]
@adamralph don't forget to mention that you would have added a stylecop rule for that too :smile:

**Comment by michaldudak** [comment]
@filipw I was just going to mention StyleCop and an idea to include its settings in the repo (and perhaps a R# settings) to enforce the code style.

**Comment by david-driscoll** [comment]
You have to remember, most of us dev on omnisharp without VS or R# :smile: 

Once we get support for loading nuget based code analyzers.... we could load the nuget based style cop rules. :smirk:

**Comment by michaldudak** [comment]
Ahh, pardon my old Windows & VS habits... ;)

**Comment by filipw** [comment]
@michaldudak tests ftw https://github.com/OmniSharp/omnisharp-roslyn/blob/master/tests/OmniSharp.Tests/CodingGuidelinesFacts.cs#L37

**Comment by nosami** [comment]
:scream:

**Comment by michaldudak** [comment]
Wow, that's an interesting approach :)

**Comment by adamralph** [comment]
It's an interesting approach, but the downside with putting it in a test is
that it has to be repeated in every solution that needs it, and would
potentially need variants for xunit, NUnit, Fixie, etc. I think I'd prefer
`Install-Package Analyzers.SpacesNotTabs`.

**Pull request merged**
