### PR TITLE
Only get first document's highlights

### PR DESCRIPTION
**Pull request by 333fred**
For files that are included in multiple projects (such as via `Compile Include` directives), we currently attempt to retrieve semantic highlights for every document. However, this means that highlight spans will have overlapping results from every project, and the service will crash. Further, we have no way of actually selecting what project to display the file as, so retrieving any but the first document doesn't serve the user. Therefore, we remove the loop, and just look through the first document found.

Fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/2421.
Fixes https://github.com/OmniSharp/omnisharp-roslyn/issues/2050.

### CODE REVIEW

**Comment by 333fred** [comment]
Note: I would highly recommend reviewing without whitespace changes, the diff is significantly smaller.

**Review by filipw — APPROVED** [review]

**Comment by filipw** [comment]
thank you!

**Comment by 333fred** [comment]
I'm going to force merge this. @filipw @JoeRobich, we need to update our mac leg, as 10.15 is deprecated, and they are intentionally starting to fail jobs. https://github.com/actions/virtual-environments/issues/5583

**Review by JoeRobich — COMMENTED** [review]
👍

**Pull request merged**
