### PR TITLE
use the full XML markup instead simple value

### LINKED ISSUE #152: XML comments often off
Our XML documentation provider misses some XML child elements. See the screen shot below

image
 
and how the value misses the actual name of the class

### PR DESCRIPTION
**Pull request by jrieken**
fixes #152 by sending the whole xml doc comment to client and not only their text node descentents

### CODE REVIEW

**Comment by nosami** [comment]
We shouldn't be returning raw xml.

**Comment by davidfowl** [comment]
Yes, I'm not sure what the client is supposed to do with this response.

**Comment by jrieken** [comment]
I am open for suggestions. Today's problem is the comments are totally broken. For instance if the mark up reads like this:

```xml
        <member name="M:TestNamespace.TestClass.GetZero">
            <summary>
            The GetZero method.
            </summary>
            <example> 
            This sample shows how to call the <see cref="M:TestNamespace.TestClass.GetZero"/> method.
            <code>
            class TestClass 
            {
                static int Main() 
                {
                    return GetZero();
                }
            }
            </code>
            </example>
        </member>
```
We produce this string: ```The GetZero method.This sample shows how to call the method.class TestClass { static int Main(){return GetZero();}}```. It gets worst when you have a method with parameters ```<param name="foo">Int32</param>``` or exceptions. For samples are here: https://msdn.microsoft.com/en-us/library/cc837134.aspx. 

So unless we come up with a way to generate meaning full plain text from those XML comments I opt for sending XML to the client and let them handle it.

**Comment by nosami** [comment]
https://github.com/OmniSharp/omnisharp-server/blob/d40bbb7a60a1e3274a124e991bcb6586371ee8c8/OmniSharp/Documentation/DocumentationConverter.cs ?

**Comment by nosami** [comment]
The other editors currently expect plain text, so this would be a breaking change.

If you need xml for formatting purposes, then we need to parameterise it.

**Comment by jrieken** [comment]
closing because @nosami has something in the works

**Pull request closed without merging**
