### PR TITLE
Update NuGet to version 5.10.0

### PR DESCRIPTION
**Pull request by grendello**
Fixes: https://github.com/OmniSharp/omnisharp-roslyn/issues/2027

Fixes the following exception when using OmniSharp on Linux (with Emacs,
but possibly breaks with other LSP clients as well):

    ERROR: OmniSharp.MSBuild.ProjectLoader, The "ResolvePackageAssets" task failed unexpectedly.
    System.MissingMethodException: Method not found: NuGet.ProjectModel.LockFileTarget NuGet.ProjectModel.LockFile.GetTarget(string,string)
      at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheReader.CreateReaderFromDisk (Microsoft.NET.Build.Tasks.ResolvePackageAssets task, System.Byte[] settingsHash)
      at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheReader..ctor (Microsoft.NET.Build.Tasks.ResolvePackageAssets task)
      at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups ()
      at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore ()
      at Microsoft.NET.Build.Tasks.TaskBase.Execute ()
      at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute ()
      at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask)

Currently used NuGet 5.2.0 is too old, update to 5.10.0 makes the issue
disappear.

### CODE REVIEW

**Comment by filipw** [comment]
can you please provide the repro steps for how you are running into this issue? I am myself on Mono 6.13 nightly build with MSBuild 16.8 and don't see this problem. 

@JoeRobich I think you once updated these Nuget dependencies but ultimately we backed off? If I recall correctly we use the older Nuget versions as those are lowest we can support. If we bump the versions we will break some of the clients.

**Comment by JoeRobich** [comment]
Well this was my understanding at the time - https://github.com/OmniSharp/omnisharp-roslyn/pull/1746#issuecomment-603629245. Wonder if we should add a global.json to our NetCoreApp2.1 test so that it builds with a 2.1 SDK in the same way as the NET5 test works.

**Comment by grendello** [comment]
> can you please provide the repro steps for how you are running into this issue? I am myself on Mono 6.13 nightly build with MSBuild 16.8 and don't see this problem.
> 
I'm using Mono 6.12 (the preview repo) with msbuild 16.6 from the same repo. Simply opening a project and using OmniSharp in LSP mode triggers the above shortly after the server starts (I'm using Emacs `lsp-mode`, didn't try `eglot`)

> @JoeRobich I think you once updated these Nuget dependencies but ultimately we backed off? If I recall correctly we use the older Nuget versions as those are lowest we can support. If we bump the versions we will break some of the clients.

If this is indeed the case, then please close my PR and this issue, I'll simply switch to Mono/nightly

**Comment by filipw** [comment]
> I'm using Mono 6.12 (the preview repo) with msbuild 16.6 from the same repo. Simply opening a project and using OmniSharp in LSP mode triggers the above shortly after the server starts (I'm using Emacs `lsp-mode`, didn't try `eglot`)

the reason why I asked, is because in the linked issue you wrote that this problem happens when you build Mono from source (with MSBuild 16.8). Building from source should be roughly similar to the 6.13 nightly.

So do you get this error when running on Mono 6.12 (+msbuild 16.6) or master build (~nightly) (+msbuild 16.8)?

**Comment by grendello** [comment]
> > I'm using Mono 6.12 (the preview repo) with msbuild 16.6 from the same repo. Simply opening a project and using OmniSharp in LSP mode triggers the above shortly after the server starts (I'm using Emacs `lsp-mode`, didn't try `eglot`)
> 
> the reason why I asked, is because in the linked issue you wrote that this problem happens when you build Mono from source (with MSBuild 16.8). Building from source should be roughly similar to the 6.13 nightly.
> 
> So do you get this error when running on Mono 6.12 (+msbuild 16.6) or source build (~nightly) (+msbuild 16.8)? Or when you say you build from master, you are actually referring to building Mono 6.12 version, not 6.13?

The original issue is correct. In my reply to you I referred to what I'm **currently** using in my setup with OmniSharp patched to use NuGet 5.8.0. Yes, I build `mono/master` and used to use it to run OmniSharp server, however something broke a couple of weeks ago with Mono itself (I haven't had time to look into it yet), so I switched to 6.12 instead.

**Comment by JoeRobich** [comment]
My earlier concern was about regressing NET Core 2.1 SDK support. Once https://github.com/OmniSharp/omnisharp-roslyn/pull/2040 merges and this branch updated, I see no problem merging this change if it is passing.

**Comment by JoeRobich** [comment]
Noticed that the wrong MSBuildSdksPath was being used for the failing .NET Core 2.1 projects. 

```
                Loading project: /tmp/hy317v4y.d81/NetCore21Project/NetCore21Project.csproj
        [dbug]: OmniSharp.MSBuild.SdksPathResolver
                Set MSBuildSDKsPath environment variable to: /home/vsts/work/1/s/.dotnet/sdk/5.0.100/Sdks
        [fail]: OmniSharp.MSBuild.ProjectLoader
                The "ResolvePackageAssets" task failed unexpectedly.
                System.MissingMethodException: Method not found: NuGet.ProjectModel.LockFile NuGet.ProjectModel.LockFileUtilities.GetLockFile(string,NuGet.Common.ILogger)
```

Tried to fix it in #2041 by having the LegacySdkResolver locate the correct SDK path.

```
                Loading project: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/9h7u5eac.5fx/NetCore21Project/NetCore21Project.csproj
        [dbug]: OmniSharp.MSBuild.SdksPathResolver
                Set MSBuildSDKsPath environment variable to: /Users/runner/work/1/s/.dotnet/sdk/2.1.811/Sdks
        [fail]: OmniSharp.MSBuild.ProjectLoader
                The "ResolvePackageAssets" task failed unexpectedly.
                System.MissingMethodException: Method not found: NuGet.ProjectModel.LockFile NuGet.ProjectModel.LockFileUtilities.GetLockFile(string,NuGet.Common.ILogger)
```

But was met with the same error. Tried a few other things but no luck.

**Comment by JordanAnthonyKing** [comment]
Is work ongoing with this?

**Comment by CitadelCore** [comment]
Seems like a couple tests are failing, but otherwise it looks done?

**Review by JoeRobich — APPROVED** [review]

**Comment by JoeRobich** [comment]
Thanks @grendello !

**Pull request merged**
