### PR TITLE
Update cake to latest version and small cleanup to the cake script on…

### PR DESCRIPTION
**Pull request by david-driscoll**
… windows

* Calling `.\build.ps1` can be called as `.\build.ps1 <target>` instead of `.\build.ps1 -Target=<target>`.

I need to see if I can make a similar change to build.sh but I'm not there just yet.

### CODE REVIEW

**Comment by filipw** [comment]
why did it trigger 4 checks?

**Comment by david-driscoll** [comment]
@filipw because I pushed against the repo, no my fork, lol.  🐑

**Comment by DustinCampbell** [comment]
@david-driscoll's a cheater :smile:

**Comment by david-driscoll** [comment]
no cheating would be pushing right into `dev` 😉

**Comment by DustinCampbell** [comment]
😺

**Pull request merged**
