### PR TITLE
GH1204: Only return usages from current file if OnlyThisFile is true

### LINKED ISSUE #1204: [Cake] Find usages returns usages from loaded files when not requested.
`/findusages` set with `OnlyThisFile: true` in request still returns usages from files included via `#load` directive. Side effects of this can be seen in image below (see highlighting):

image

Request:
```
{
  "Type": "request",
  "Seq": 339,
  "Command": "/findusages",
  "Arguments": {
    "FileName": "c:\\Users\\mb\\src\\tmp\\test\\includederror.cake",
    "Line": 18,
    "Column": 11,
    "OnlyThisFile": true,
    "ExcludeDefinition": false
  }
}
```

Response:
```
{
  "Request_seq": 339,
  "Command": "/findusages",
  "Running": true,
  "Success": true,
  "Message": null,
  "Body": {
    "QuickFixes": [
      {
        "FileName": "B3437BF2-8AE3-4281-8726-B926BB9DF75D",
        "Line": 8039,
        "Column": 13,
        "EndLine": 8039,
        "EndColumn": 24,
        "Text": "public void Information(System.String value)",
        "Projects": [
          "includederror.cake"
        ]
      },
      {
        "FileName": "c:\\Users\\mb\\src\\tmp\\test\\error.cake",
        "Line": 5,
        "Column": 1,
        "EndLine": 5,
        "EndColumn": 12,
        "Text": "Information(\"Running tasks...\");",
        "Projects": [
          "includederror.cake"
        ]
      },
      {
        "FileName": "c:\\Users\\mb\\src\\tmp\\test\\error.cake",
        "Line": 7,
        "Column": 1,
        "EndLine": 7,
        "EndColumn": 12,
        "Text": "Information(\"Running tasks...\");",
        "Projects": [
          "includederror.cake"
        ]
      },
      {
        "FileName": "c:\\Users\\mb\\src\\tmp\\test\\includederror.cake",
        "Line": 18,
        "Column": 4,
        "EndLine": 18,
        "EndColumn": 15,
        "Text": "Information(\"Running tasks...\");",
        "Projects": [
          "includederror.cake"
        ]
      },
      {
        "FileName": "c:\\Users\\mb\\src\\tmp\\test\\includederror.cake",
        "Line": 24,
        "Column": 4,
        "EndLine": 24,
        "EndColumn": 15,
        "Text": "Information(\"Finished running tasks.\");",
        "Projects": [
          "includederror.cake"
        ]
      },
      {
        "FileName": "c:\\Users\\mb\\src\\tmp\\test\\includederror.cake",
        "Line": 33,
        "Column": 4,
        "EndLine": 33,
        "EndColumn": 15,
        "Text": "Information(\"Hello Cake!\");",
        "Projects": [
          "includederror.cake"
        ]
      }
    ]
  },
  "Seq": 508,
  "Type": "response"
}
```

### PR DESCRIPTION
**Pull request by mholo65**
-Fixes #1204

### CODE REVIEW

**Comment by mholo65** [comment]
Rebased and fixed conflicts.

**Comment by mholo65** [comment]
Rebased. I'll merge once CI passes.

**Comment by filipw** [comment]
> Rebased. I'll merge once CI passes.

you need to resolve the conflicts on the changelog again 😀

**Comment by mholo65** [comment]
>you need to resolve the conflicts on the changelog again..

Have I ever told you about GitReleaseManager? (https://github.com/GitTools/GitReleaseManager) 😄

**Pull request merged**
