### PR TITLE
Add logic to set MSBuildExtensionsPath to Mono's xbuild directory

### LINKED ISSUE #892: Question About Xamarin.iOS.dll Support
I am hoping it is something I am looking over that is extremely obvious, but I can run just about any project with OmniSharp on Mac OS Sierra 10.12.5 with the exception of one with the Xamarin.iOS.dll in it. When I run it I get the error: 

`The reference assemblies for framework "Xamarin.iOS,Version=v1.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.`

I have the SDK installed and actually have access to the DLL in question- is there a way for me to include external DLLs like this in solutions run on OmniSharp? I tried just adding it to the GAC with `gacutil -i Xamarin.iOS.dll` which was given from [mono-project](http://www.mono-project.com/docs/advanced/assemblies-and-the-gac/) but that did not work either. Anything to nudge me in the right direction would be appreciated. Thanks!

### PR DESCRIPTION
**Pull request by DustinCampbell**
I'm cherry-picking this change from https://github.com/OmniSharp/omnisharp-roslyn/pull/915, since it's unrelated to that PR.

Fixes #892 
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1597
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1624
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1396

Related PR: https://github.com/mono/msbuild/pull/22

### CODE REVIEW

**Comment by DustinCampbell** [comment]
Got additional changes coming for this.

**Comment by filipw** [comment]
I kicked off the build again

**Comment by DustinCampbell** [comment]
@filipw: This isn't ready yet. Got another important change coming that actually fixes this.

**Comment by filipw** [comment]
👍

**Comment by DustinCampbell** [comment]
@filipw: Do you want to take another look?

**Comment by filipw** [comment]
looks good! 
maybe at some point we can allow passing in mono locations too, in case you run a customized build or a local from a custom location

**Comment by DustinCampbell** [comment]
@filipw: Maybe. I'm not sure that's a very common scenario though. At least, I've never heard an ask for it.

**Comment by DustinCampbell** [comment]
OK. Got one more change to make.

**Comment by DustinCampbell** [comment]
OK. I've done more testing on this today and it seems to work reasonably well.

**Pull request merged**
