### PR TITLE
Integrate with dotnet-cli

### PR DESCRIPTION
**Pull request by troydai**
Here's a list of the changes included in this PR:

1. A new powershell build script on windows. (`build.ps1`)
2. Adjust the NuGet feed
3. Adjust the solution file.
4. Use `dotnet-cli` tool chain to build, test and publish.
5. Add `DotNetProjectSystem`
6. Integrate the new `PlatformAbstractions` and `DependencyModel` (https://github.com/aspnet/Announcements/issues/149)

Additional work required are in this TODO list:

- [x] Implement package restore
- [x] Refurbish `build.sh`
- [x] Get build pass on Traves / AppVeyor (Partially done. NETCore platform is not supported on osx 10.9, which is used in Travis. I’m looking for a solution.)
- [x] Remove `OmniSharp.DNX`!
- [x] Make a decision on `dnx451` target framework (Add support for it or remove the target framework entirely)
- [x] Add `dnx451` target to `OmniSharp.DotNet` ~~(Blocked: https://github.com/dotnet/cli/pull/1357)~~
- [x] ~~Pass build on osx 10.9~~ Use osx 10.10 image.

/cc @david-driscoll @davidfowl

### CODE REVIEW

**Comment by david-driscoll** [comment]
From the last meeting, as long as project.json projects will mostly work with the `cli`

**Comment by david-driscoll** [comment]
* From the last meeting, I remember that it sounded like `project.json` based projects would work with the `cli` tooling, so I'm okay dropping `OmniSharp.DNX`.
* Are there any blockers related to cross compiling against mono / desktop clr / coreclr?
  * The goal is to make things all work on the coreclr, but in theory support for all 3 should be fairly simple.

**Comment by troydai** [comment]
I'm not aware of and blocker at this point. I can use dotnet to compile DNXCore50 and DNX451 targets just fine.

**Comment by filipw** [comment]
i'm getting the following error when building this branch, is it expected?

```
Error: Unable to load application or execute command 'test'.
Tests failed for src/OmniSharp.Bootstrap.Tests with runtime clr
```

**Comment by troydai** [comment]
@filipw it is not expected. can you sync to the latest and try again? run `build.ps1` please.

**Comment by troydai** [comment]
@david-driscoll I’m working on the `build.sh` now.

**Comment by troydai** [comment]
Ping @david-driscoll

**Comment by david-driscoll** [comment]
I assume this warning is just semantics (things are moving to `rc3`?)

> dotnet.exe : C:\projects\omnisharp-roslyn\tests\OmniSharp.Stdio.Tests\project.json(17,52): warning NU1007: Dependency specified was System.Runtime.Serialization.Primitives >= 4.1.0-rc2-* but ended up with 
System.Runtime.Serialization.Primitives 4.1.0-rc3-23811.
At C:\projects\omnisharp-roslyn\build.ps1:38 char:3
+   & $dotnet publish ./tests/$project --output $target --framework dnxcore50 |
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\pro...3811.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by david-driscoll** [comment]
With appveyor passing, I'll see if I can give a test pass with atom tonight, see how things are operating.  The last thing we need to do is get things zipped up after publishing, which should be fairly simple to pull from the old build script.

**Comment by troydai** [comment]
I’ll take a look the `rc3` thing. No we should have rc3 build at this point.

**Comment by troydai** [comment]
@david-driscoll if you want to try the build, try out the __dnxcore50__ version first. There is binary rebinding issue on __dnx451__ which I’m looking into.

**Comment by david-driscoll** [comment]
Something I noticed, if `dotnet` is not in the users Path then the PackageRestoreTool starts to have issues.  Or if the `dotnet` that is in the path is an older version it can cause problems as well.

Not sure what the solution is for that, I don't know if it's a big blocker, but we should maybe have some way to detect if the command is available.  If it isn't maybe just not do anything.

**Comment by david-driscoll** [comment]
I was also seeing some of these diagnostics.
image

I assume it's loading both the compiled dll in the bin and the source on disk.  Looks like `ProjectContextLens` might be somewhat responsible here?   I haven't dug too much into it yet.

**Comment by troydai** [comment]
@david-driscoll I agree the logic of searching for tool and validate version can be more robust. Should `dotnet` is not on the path, we should send error response. In that case what event should be sent?

Regarding to the issue 2. I'll take a look. What's the project you were tested against?

**Comment by david-driscoll** [comment]
@troydai I was working with the OmniSharp solution itself.

**Comment by troydai** [comment]
@david-driscoll gotcha. I'll try it out tonight.

**Comment by troydai** [comment]
Test Matrix:

1. OmniSharp CLR Windows
2. OmniSharp CoreCLR Windows
3. OmniSharp CLR with Mono Mac OSX (10.10+)
4. OmniSharp CoreCLR Mac OSX (10.10+)
5. OmniSharp CLR with Mono Linux
6. OmniSharp CoreCLR Linux

**Comment by troydai** [comment]
@david-driscoll recent changes in xunit breaks all the tests. I'm updating the branch to adopt the latest test packages.

**Comment by troydai** [comment]
@david-driscoll @davidfowl @sayedihashimi @DustinCampbell 
Guys. The work on dotnet-cli integration mostly done here. I think we should set up a plan for merging it to master and communicate the changes to downstream plugins. The things we should decide:
- [ ] When do we merge. 
- [ ] What level of quality control we should impose.
- [ ] Significant scenarios?
- [ ] How to distribution.
- [ ] Strategy of pinning versions.
- [ ] Clone feeds (so target the pinned packages won't be erased).

Let's schedule a meeting sometime tomorrow.

**Comment by filipw** [comment]
at this point there is not much that needs to be planned anymore since master is broken anyway :smile: 

The main thing I'd suggest is to not use `-*` dependencies as they are bound to break soon again, especially in this volatile world.

**Comment by david-driscoll** [comment]
I would love to have some sort of mirror of the myget feed(s) used to build, so that we can keep master in a stable state.  I'm going to be testing today when I get a chance to see how things are working.  I had some small issues with Atom the other day, but it's been a few days.

**Comment by DustinCampbell** [comment]
FWIW, I was able to build Troy's bits and the dnx451 target worked for my in VS Code.

**Comment by troydai** [comment]
I'll close this PR and delete `troy/use.dotnet` branch. All the `dotnet-cli` development goes into `dotnet` branch.

**Pull request closed without merging**
