### PR TITLE
Don't run GitVersion locally

### LINKED ISSUE #1891: Cant build
This is the code

<pre><font color="#CC0000"><b>$ </b></font><font color="#4E9A06">./build.sh</font>
Feeds used:
  /home/goldenhuaji/.nuget/packages/
  https://api.nuget.org/v3/index.json
  https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
  https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
  https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json
  https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5-transport/nuget/v3/index.json
  https://www.myget.org/F/omnisharp/api/v3/index.json

/home/goldenhuaji/.cache/vimfiles/repos/github.com/OmniSharp/omnisharp-vim/omnisharp-roslyn-server/tools/packages.config 中列出的所有程序包均已安装。
<span style="background-color:#2E3436"><font color="#FCE94F">/home/goldenhuaji/.cache/vimfiles/repos/github.com/OmniSharp/omnisharp-vim/omnisharp-roslyn-server/build.cake(48,20): warning CS0618: &apos;ITFBuildProvider.IsRunningOnTFS&apos; is obsolete: &apos;Please use ITFBuildProvider.IsRunningOnAzurePipelines instead.&apos;</font></span>
<span style="background-color:#CC0000"><font color="#EEEEEC">Error: </font></span><span style="background-color:#EF2929"><font color="#EEEEEC">One or more errors occurred. (GitVersion: Process returned an error (exit code 1).)</font></span>
	<span style="background-color:#EF2929"><font color="#EEEEEC">GitVersion: Process returned an error (exit code 1).</font></span>
</pre>

### PR DESCRIPTION
**Pull request by mholo65**
- Don't run GitVersion locally
- Use static version when running locally
- If you want GitVersion locally, install GitVersion (https://www.nuget.org/packages/GitVersion.Tool/) and run
  `dotnet gitversion /output buildserver` before running build.ps1/build.sh

Should fix #1891

**For some reason GitVersion is not outputting env vars when I run locally. So I can't seem to get the last step working :(**

### CODE REVIEW

**Comment by mholo65** [comment]
Another option is that we move to use [`GitVersion.Tool`](https://www.nuget.org/packages/GitVersion.Tool/), but that would require us to reorder some of the Tasks, to make sure the .NET SDK specified in `global.json` is installed before attempting to install, or use GitVersion.Tool..

**Comment by sonnguyen9800** [comment]
>     * Don't run GitVersion locally
> 
>     * Use static version when running locally
> 
>     * If you want GitVersion locally, install GitVersion (https://www.nuget.org/packages/GitVersion.Tool/) and run
>       `dotnet gitversion /output buildserver` before running build.ps1/build.sh
> 
> 
> Should fix #1891
> 
> **For some reason GitVersion is not outputting env vars when I run locally. So I can't seem to get the last step working :(**

My system (Ubuntu 20.04) cannot run this code, the log output shows the errors:

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-gitversion.tool does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Comment by sonnguyen9800** [comment]
By a miracle, i could run the command "dotnet gitversion /output buildserver",

The log looks like this:

"
123@123~/Downloads/omnisharp-roslyn$ dotnet gitversion /output buildserver
INFO [10/07/20 15:56:58:91] Working directory: /home/sonnguyen9800/Downloads/omnisharp-roslyn
INFO [10/07/20 15:56:58:94] Project root is: /home/sonnguyen9800/Downloads/omnisharp-roslyn/
INFO [10/07/20 15:56:58:94] DotGit directory is: /home/sonnguyen9800/Downloads/omnisharp-roslyn/.git
INFO [10/07/20 15:56:58:96] Begin: Loading version variables from disk cache
  INFO [10/07/20 15:56:58:97] Begin: Deserializing version variables from cache file /home/sonnguyen9800/Downloads/omnisharp-roslyn/.git/gitversion_cache/5103F2D91E6EEF8E89015D37DF141357A457C87D.yml
  INFO [10/07/20 15:56:59:02] End: Deserializing version variables from cache file /home/sonnguyen9800/Downloads/omnisharp-roslyn/.git/gitversion_cache/5103F2D91E6EEF8E89015D37DF141357A457C87D.yml (Took: 52.26ms)
  INFO [10/07/20 15:56:59:02] End: Loading version variables from disk cache (Took: 52.97ms)
  INFO [10/07/20 15:56:59:03] Done writing 

"

However, when build the program, the same error shown:

"Feeds used:
  /home/sonnguyen9800/.nuget/packages/
  https://api.nuget.org/v3/index.json
  https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
  https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
  https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json
  https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5-transport/nuget/v3/index.json
  https://www.myget.org/F/omnisharp/api/v3/index.json

All packages listed in /home/sonnguyen9800/Downloads/omnisharp-roslyn/tools/packages.config are already installed.
/home/sonnguyen9800/Downloads/omnisharp-roslyn/build.cake(48,20): warning CS0618: 'ITFBuildProvider.IsRunningOnTFS' is obsolete: 'Please use ITFBuildProvider.IsRunningOnAzurePipelines instead.'
Error: One or more errors occurred. (GitVersion: Process returned an error (exit code 1).)
	GitVersion: Process returned an error (exit code 1).
"
"

**Comment by mholo65** [comment]
Superseeded by #2030

**Pull request closed without merging**
