### PR TITLE
[wip] Cli

### PR DESCRIPTION
**Pull request by david-driscoll**
Dropped in @troydai's branch on the main repo

### CODE REVIEW

**Comment by troydai** [comment]
@david-driscoll the change on the branch is way too big to be reviewed. can we get the first 2 dozens of commits in the master branch and then integrate the CLI project system gradually?

**Comment by david-driscoll** [comment]
I don't want to merge any of the beta 8 stuff because it never worked, I'm fine with squashing all the commits to remove some noise though.  I was trying to get it building on my machine last night but I ran into an exception thrown by csc.

**Comment by troydai** [comment]
Ok. I will fork a new branch from the master and rebuild my changes over there. I believe it will be faster and easier.

**Comment by david-driscoll** [comment]
Sounds good, let me know when it's ready, and I'll work on the travis build
stuff.

**Comment by david-driscoll** [comment]
Troy has a different branch, I'll close this and open a PR for tracking the other branch.

**Pull request closed without merging**
