### PR TITLE
[wip] Cli

### PR DESCRIPTION
**Pull request by david-driscoll**

### CODE REVIEW

**Comment by troydai** [comment]
@david-driscoll @davidfowl 

Till the commit https://github.com/OmniSharp/omnisharp-roslyn/commit/61b3cfe08bb2a66db2d25499f7b2d0a2225f28fc I upgrade all the projects to use the latest __r2__ packages (both ASP.NET and CoreCLR). Travis and AppVeyor both passed. 

A few tests are skipped though since some refactorying are blocked because __Roslyn__ is updated to `1.1.1` as well.

I recommend us to check in this commit first so the __master__ branch begin running on rc2 and the crew can participate in maintaining it. In the meantime I can work on porting `OmniSharp.DotNet`.

**Comment by david-driscoll** [comment]
I'll give it a run through today / tonight.

**Comment by david-driscoll** [comment]
@troydai if you don't want be blocked, we can branch all these changes to `update-rc2`, and I can test from there.

**Comment by troydai** [comment]
@david-driscoll take your time.

I’ll branch these to `update-rc2` and keep working on the `cli` port in this branch.

**Comment by david-driscoll** [comment]
perfect, then I can look at it tonight. :+1:

**Pull request closed without merging**
