### PR TITLE
Added an .editorconfig to dictate project formatting settings

### PR DESCRIPTION
**Pull request by Mpdreamz**
Every editor under the sun supports (or should!) http://editorconfig.org/ 

Visual studio has an extension: https://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328

This will force your editor settings to be changed when working on our project to the settings we dictate. 

Editorconfig will leave your defaults alone, so when you switch back to a private project with no editorconfig file it will keep using your default settings there.

Ties into #70

### CODE REVIEW

**Comment by nosami** [comment]
kproj files are indented by 2 spaces. I don't think anyone would ever edit those, but it should probably be added.

**Comment by khellang** [comment]
I think [corefx's .editorconfig](https://github.com/dotnet/corefx/blob/master/.editorconfig) makes more sense, maybe something like:

```
# EditorConfig is awesome:
http://EditorConfig.org

# top-most EditorConfig file
root = true

[*]
insert_final_newline = true
indent_style = space
indent_size = 2
trim_trailing_whitespace = true

[*.cs]
indent_size = 4

[*.{csproj,kproj,nuspec}]
indent_size = 2
```

**Comment by nosami** [comment]
@khellang looks good to me.

**Comment by Mpdreamz** [comment]
:+1: thanks @khellang  will update the PR shortly 

That url should also be quoted though, even if editorconfig files can handle invalid keys (part of its test suite).

**Comment by Mpdreamz** [comment]
Updated, do we care about squashing and rebasing?

**Comment by nosami** [comment]
nah! thanks!

**Comment by jrieken** [comment]
:+1:

**Comment by jrieken** [comment]
@Mpdreamz didn't you also do an API (editor config nuget package) so that we can seed the roslyn formatter with those settings?

**Comment by Mpdreamz** [comment]
I did, I just updated it today so that it includes a proper aspnetcore50 build in the nuget package. Just did a `git checkout -b feature/editorconfig-powered-formatting` to start on #31 :)

**Comment by Mpdreamz** [comment]
It wont actually seed once though, it will lookup **everytime** since thats the editorconfig way, i.e you might very well have different settings for `*.generated.cs` vs `*.cs` files. 

Usually an editor opens a file and seeds that file with editorconfig settings, but we dont track editors opening and closing files on the server right? or do we?

**Comment by jrieken** [comment]
yeah - that's what I meant. we should have a thing (service?) which returns an OptionSet that applies to the current file.

**Pull request merged**
