### PR TITLE
Remove not used middleware extension methods and unify adding middleware

### PR DESCRIPTION
**Pull request by cieciurm**
Hi,

I was browsing through the code and noticed that in the HTTP server, the middlewares are added directly using `UseMiddleware<T>` and not through the extension methods except for `LoggingMiddleware`, which is using the extension method.

Here's my PR with a suggestion to unify this code.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/OmniSharp/omnisharp-roslyn?pullRequest=2340) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/OmniSharp/omnisharp-roslyn?pullRequest=2340) before we can accept your contribution.<br/><br/>:x: cieciurm [sign now](https://cla.dotnetfoundation.org/OmniSharp/omnisharp-roslyn?pullRequest=2340)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/OmniSharp/omnisharp-roslyn?pullRequest=2340) it.</sub>

**Review by filipw — APPROVED** [review]
thanks

**Comment by cieciurm** [comment]
Hi @filipw,

Can this be merged or is there something missing?

**Comment by cieciurm** [comment]
Hi @filipw,

Can this be merged or is there something missing?

**Comment by cieciurm** [comment]
Hi @filipw,

Can this be merged or is there something missing?

**Comment by cieciurm** [comment]
Hi @filipw ,

Can this be merged or is there something missing?

**Comment by filipw** [comment]
thanks!

**Pull request merged**
