### PR TITLE
End of life for .NET Core 1.0 / 1.1 (project.json)

### PR DESCRIPTION
**Pull request by filipw**
.NET Core 1.0/1.1 reached end of life and went out of support on [27 June 2019](https://devblogs.microsoft.com/dotnet/net-core-1-0-and-1-1-will-reach-end-of-life-on-june-27-2019/).

We discussed this a while back and we have disabled the `project.json` features by default already last summer (they were opt-in), and we said we will wait with complete removal until EOL is reached.
I think now is a good time to pull the trigger.

This PR:
 - removes `project.json` project system support
 - removes `project.json` test manager support
 - removes `project.json` test assets
 - adjusts the build script accordingly

@rchande @akshita31 if you have any concerns based one the telemetry of the C# extension for VS Code please shout 😀

### CODE REVIEW

**Comment by david-driscoll** [comment]
@rchande any input on this?

**Comment by rchande** [comment]
@david-driscoll @filipw I thought I commented on this on Monday but somehow failed to submit or something.

Anyway, I looked at our telemetry and there's no indication that anyone used C# extension with a .NET Core 1.0 project in the last 2 months (that's how far back we keep telemetry).

**Comment by filipw** [comment]
rebased and resolved conflicts - should be good to go!

**Comment by david-driscoll** [comment]
End of an era....

**Pull request merged**
