### PR TITLE
Ensure that MSBuildProjectSystem doesn't add project references twice

### LINKED ISSUE #795: Lots of errors when opening aspnet/SignalR
I'm running on OSX.

I didn't want to open an uber issue but it seems like there are multiple things happening here. The repro steps are to clone https://github.com/aspnet/SignalR and run build.sh. After the build finishes, open vs code at the root (`code .`).

1. I get warnings telling me there are unresolved dependencies even though restore ran.
2. I get 100s of errors talking about ambiguous references. It seems as though the sample projects don't see the src projects within the same solution so packages are being resolved...

image

I'll try to pick it apart into specific issues but I was caught by surprise because I thought things would just work.

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #795

It's possible for project references to appear twice within an MSBuild project after execution:

* As a ProjectReference item
* As a ReferencePath item with ReferenceSourceTarget="ProjectReference"

This change makes sure that ReferencePath items that were sourced from project references aren't added. We just use the project references, which is a better experience at designtime when the project is built.

Note: There was code that used to do this, but it was unintentionally removed in a refactoring a few months ago (by me -- oops!): https://github.com/OmniSharp/omnisharp-roslyn/commit/ef4b3838d39666ed5ca9780ea133bfdc08ff5844.

### CODE REVIEW

**Comment by filipw** [comment]
have you thought of publishing all this MSBuild-related code as a nuget package? 

For example I would like to use something like that in other projects - being able to go from `csproj` to everything needed to create a `CSharpCompilation`/describing the project (some kind of a replacement for https://www.nuget.org/packages/Microsoft.DotNet.ProjectModel)

**Comment by DustinCampbell** [comment]
> have you thought of publishing all this MSBuild-related code as a nuget package?

Probably not. We already have that in Roslyn with the [MSBuildProjectLoader](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Desktop/Workspace/MSBuild/MSBuildProjectLoader.cs). It just doesn't work with the latest MSBuild and isn't portable. However, it's looking likely that I'll be called upon to fix that.

**Comment by filipw** [comment]
oh that's what I've been missing. Is it part of any of the Roslyn nuget packages?

**Comment by DustinCampbell** [comment]
Sure, but it's only available on desktop: https://www.nuget.org/packages/Microsoft.CodeAnalysis.Workspaces.Common/.

The API sits next to MSBuildWorkspace.

**Comment by filipw** [comment]
thanks!

**Pull request merged**
