### PR TITLE
Update versions to match .NET SDK 6 RC1 (fix test)

### PR DESCRIPTION
**Pull request by JoeRobich**
Attempt to fix test failure in https://github.com/OmniSharp/omnisharp-roslyn/pull/2217

### CODE REVIEW

**Comment by JoeRobich** [comment]
@filipw @nohwnd PTAL

**Review by filipw — APPROVED** [review]
looks legit thanks

**Comment by filipw** [comment]
FWIW this would be my fix too, though I wouldn't be able to explain why 😅

**Comment by JoeRobich** [comment]
Basically I have been pulling most of the NuGet libraries from the Microsoft.NET.Sdk package since they would all be version matched and that save a lot of repetition in the packages.config. In this case the NuGet packages in the Sdk package don't include this API change. We can revert my change once we move to a newer Sdk package that includes the change.

**Pull request merged**
