### PR TITLE
Goto symbol metadata

### PR DESCRIPTION
**Pull request by david-driscoll**
Extension of #261

cc @Andorbal @nosami

### CODE REVIEW

**Comment by david-driscoll** [comment]
I need to make the metadata end point give us source, but currently you'll get a response like:

```
{
    FileName: "#/metadata/Microsoft.CodeAnalysis.Text.LinePosition",
    Line: 40,
    Column: 19
}
```

The intent would be the consume client would follow #/metadata/... and hit the metadata controller with the symbol of `Microsoft.CodeAnalysis.Text.LinePosition`.  This will allow editors to have a way to access the metadata source without going through goto definition (or hopefully emitting the file to disc).

**Comment by david-driscoll** [comment]
Travis is complaining about... I have no idea what's going on, the tests did pass though.  Same error on Appveyor... now I'm really confused.

@nosami any ideas?

```
Bundling runtime dnx-mono.1.0.0-beta4
Unable to locate published package OmniSharp in NuGet.PhysicalFileSystem
System.IO.DirectoryNotFoundException: Could not find a part of the path "/home/travis/build/OmniSharp/omnisharp-roslyn/artifacts/build/omnisharp/approot/packages/OmniSharp/1.0.0/root/project.lock.json".
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) [0x00000] in <filename unknown>:0 
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share) [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
  at Microsoft.Framework.Runtime.DependencyManagement.LockFileFormat.Write (System.String filePath, Microsoft.Framework.Runtime.DependencyManagement.LockFile lockFile) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.PackageManager.Publish.PublishProject.UpdateLockFile (Microsoft.Framework.PackageManager.Publish.PublishRoot root) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.PackageManager.Publish.PublishProject.PostProcess (Microsoft.Framework.PackageManager.Publish.PublishRoot root) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.PackageManager.Publish.PublishRoot.Emit () [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.PackageManager.Publish.PublishManager.Publish () [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.PackageManager.Program+<>c__DisplayClass3_2.<Main>b__4 () [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute (System.String[] args) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.PackageManager.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
Build failed.
```

**Comment by nosami** [comment]
I think this could be because I ran the release manually last time from my machine because Travis was broken? Maybe there were some residual files. I'll run another release now that Travis is fixed.

**Comment by david-driscoll** [comment]
It was an error in the code for dnxcore (async without await).

**Comment by david-driscoll** [comment]
@nosami I've added a 2 second cancellation token, hopefully that will stop the cpu from running away on mono.  I'll have to try and get a better linux vm setup for testing.

**Comment by nosami** [comment]
A long and very boring gif

metadata-high-cpu

CPU goes to 100% after one request, 200% after 2 requests. It does come back down eventually.

**Comment by nosami** [comment]
There's another problem with this. It's using the Features dll... and that changed to .net 4.6 in -rc3. 

.net 4.6 isn't supported by mono yet :(

**Comment by david-driscoll** [comment]
I know, but the feature is just sooooo awesome!!! We needs it! :zap: (That said it can wait for now :smile: )

**Comment by nosami** [comment]
Awesome! Thanks @Andorbal @david-driscoll :)

**Pull request merged**
