### PR TITLE
Squashed copy of https://github.com/OmniSharp/omnisharp-roslyn/pull/1076/files

### PR DESCRIPTION
**Pull request by rchande**

### CODE REVIEW

**Comment by filipw** [comment]
we can squash on merge too when we merge the original PR - not sure this new PR is needed

**Comment by savpek** [comment]
Yes PR can be directly squashed to master, intermediate steps not needed. Well theres exception: if squash is blocked from repository settings then it cannot be done.

**Comment by filipw** [comment]
> if squash is blocked from repository settings

it's allowed here 🙂

**Comment by rchande** [comment]
I did this in order to use a Microsoft-internal code review tool that's I find easier to read than GitHub. That tool has a limitation of only being able to deal with PRs that contain 64 or fewer commits and @savpek has many more than that :)

**Comment by filipw** [comment]
ah that is true 😃

**Comment by david-driscoll** [comment]
Closing for now, feel free to reopen if you need @rchande

**Pull request closed without merging**
