### PR TITLE
Adds the symbol kind to /findsymbols

### PR DESCRIPTION
**Pull request by nosami**
Adds the symbol kind to /findsymbols and added DiagnosticsLocation class

### CODE REVIEW

**Comment by aeschli** [comment]
@nosami - Just saw this: SymbolFinder.FindSourceDeclarationsAsync ls takes a parameter SymbolFilter. So you can write 
await SymbolFinder.FindSourceDeclarationsAsync(_workspace.CurrentSolution, predicate, SymbolFilter.TypeAndMember);
and will not get any namespaces

**Comment by nosami** [comment]
@aeschli nice! updated.

**Comment by aeschli** [comment]
Thanks a lot. Another issue, although not directly related to this PR (sorry for the misuse, I'm happily opening a new issue if you prefer). All void method labels get a semicolon added to their labels.
See last lines of SnippetGenerator.RenderMethodSymbol

**Comment by nosami** [comment]
ah, ok - that's used by intellisense and I'm reusing the same code.

**Comment by nosami** [comment]
@aeschli fixed.

**Comment by jrieken** [comment]
LGTM

**Comment by aeschli** [comment]
@nosami Cool, thanks, tried it out - looks nice!

**Comment by nosami** [comment]
:+1:

**Pull request merged**
