### PR TITLE
Update gitversion and tweak config to avoid version increments from merge commits

### PR DESCRIPTION
**Pull request by mholo65**
Note, only updating GitVersion solved the issue, but after discussing with @gep13 the changes I made to the config also makes sense. Only updating config didn't work (seems to be a bug in v4 of GitVersion regarding merge-commits).

### CODE REVIEW

**Comment by mholo65** [comment]
One easy workaround would be to just ignore 4ffabfa8d8279cd5afa17912143cec9612f77020, but that would not prevent this happening again.

**Comment by filipw** [comment]
which version does it now resolve to?

**Comment by mholo65** [comment]
`1.32.19-beta6` and with this commit it should be `beta7` also tested creating a branch named `2.5.4` and then it resolved to `2.5.4`

**Comment by mholo65** [comment]
You can also see from AppVeyor history that it works https://ci.appveyor.com/project/david-driscoll/omnisharp-roslyn/history

**Comment by filipw** [comment]
ok excellent! 
Any idea what caused the 3.5.x here https://dev.azure.com/omnisharp/Builds/_build/results?buildId=319? since some builds resolved to 3.1.x and some to 3.5.x

**Comment by mholo65** [comment]
We run `/diag` on ADO with GitVersion, here's the commit:
```
Update build tools')
  INFO [04/15/19 17:52:48:94] Base version used: Merge message 'Merge pull request #699 from DustinCampbell/update-nuget-to-3.5.0
```

Also noticed we download another GitVersion version as ADO build step, will need to fix that as well.

**Comment by mholo65** [comment]
@filipw you can now see that ADO is also fixed [here](https://dev.azure.com/omnisharp/Builds/_build/results?buildId=327) Check the `Run GitVersion` task in `GitVersion Job`.

**Comment by rchande** [comment]
@mholo65 Thanks a lot!

**Pull request merged**
