### PR TITLE
Produce an arm64 Linux package

### PR DESCRIPTION
**Pull request by JoeRobich**

### CODE REVIEW

**Comment by filipw** [comment]
looks exciting 😀

**Comment by david-driscoll** [comment]
this sounds shiny

**Comment by filipw** [comment]
@JoeRobich is this still alive?

**Comment by JoeRobich** [comment]
This isn't ready yet. I feel like it is increasingly unavoidable but at the moment I can't give it attention.

My current thoughts are that it is ok for the build.cake to package up managed assets for the included msbuild, but for native libraries we should be collecting them separately. The obvious place would be to grab the native msbuild libraries when we create the mono packages. At that point we could build the arm packages even when running on x86 in the cloud.

**Comment by carlossanlop** [comment]
Any updates on this @JoeRobich @filipw?

The dotnet/runtime team has been aggressively working on adding Arm64 support to the .NET libraries for the last couple of months (see the [issues](https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+label%3Aarch-arm64) and [PRs](https://github.com/dotnet/runtime/pulls?q=is%3Apr+label%3Aarch-arm64+)). Unfortunately, it's been somewhat difficult to debug our code in WSL2 because of the lack of ARM64 support from the Omnisharp extension.

Do you need help with testing? I can ask the ARM feature crew if they would be open to helping debug the extension if this package is generated.

**Comment by JoeRobich** [comment]
@carlossanlop, unfortunately this was exploratory work and not something we are prioritizing at the moment. I know there is a remote debugging experience where the debugger attaches over ssh (see https://github.com/OmniSharp/omnisharp-vscode/wiki/Remote-Debugging-On-Linux-Arm#remotely-debug-your-application). @gregg-miskelly Might have some ideas if that isn't working for you.

cc: @cartermp & @vatsalyaagrawal

**Comment by JoeRobich** [comment]
This will be revisited later.

**Comment by shaunawins** [comment]
Curious, is it possible to build OmniSharp on/for arm64 linux at all right now? I was considering attempting it, but I don't want to be wasting my time if there are hurdles I won't be able to clear without a great deal of knowledge that I don't have at the moment.

**Pull request closed without merging**
