### PR TITLE
Move OmniSharp to target net46 only

### LINKED ISSUE #666: Integrate embedded Mono runtime and MSBuild into OmniSharp
For the latest release of omnisharp-vscode, we have made significant changes to how OmniSharp runs that need to be integrated back into omnisharp-roslyn. The following are the key components the need to be integrated.

* **MSBuild**: In order to properly target .NET Core, .NET Framework and Mono .csproj projects, OmniSharp must include MSBuild itself along with relevant targets and task. On Windows, this can be achieved with the [Microsoft.Build.Runtime](https://www.nuget.org/packages/Microsoft.Build.Runtime/15.1.0-preview-000370-00) package. On macOS/Linux, we need a similar but different set of content. In omnisharp-vscode, this achieved by using a custom build from Xamarin's [fork of MSBuild](https://github.com/mono/msbuild/tree/xplat-c9). Because both of these MSBuild variants target net46 but are completely different, we'll need custom build logic to pull them into OmniSharp.

* **Embedded Mono Runtime**: omnisharp-vscode no longer uses .NET Core builds of OmniSharp. Instead, it runs OmniSharp as a net46 app. On Windows, it just runs on the installed .NET Framework. On macOS/Linux, it runs on an embedded Mono runtime with a set of Mono framework assemblies. There are three variants of the Mono runtime: one for macOS, one for Linux/x86, and one for Linux/x64.

Once the integration is complete, there should only be 5 different builds of OmniSharp:

* Windows (x86 and x64)
* OSX
* Linux (x86 and x64)

In addition, OmniSharp will be able to support the following project types:

* project.json (legacy)
* .csproj targeting .NET Core (new)
* .csproj targeting .NET Framework
* .csproj targeting Mono

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #666

*Tagging @david-driscoll and @filipw specifically for a review since this is a significant change. It'd be great if anyone looking at this could build this branch and try it out.*

This PR moves OmniSharp to target .NET Framework 4.6 exclusively and removes all of the netcoreapp1.1 builds. With this change, there are now only six flavors of OmniSharp that will be released:

* Windows builds that run on Desktop CLR.
    * omnisharp-win-x86.zip
    * omnisharp-win-x64.zip
* A *Nix build that be run on Mono 5.2.0 or greater. (Note that the `--assembly-loader=strict` flag must be specified when launch this build with Mono).
    * omnisharp-mono.tar.gz
* Standalone builds for OSX and Linux that include the Mono bits necessary to run OmniSharp.
    * omnisharp-osx.tar.gz
    * omnisharp-linux-x86.tar.gz
    * omnisharp-linux-x64.tar.gz

**Important note** This change does *not* affect the project types that OmniSharp supports. OmnISharp still supports .NET Core and .NET Framework, and Xamarin, Unity and other Mono-based projects.

**For discussion**: I chose to *not* include `libuv.dll` in the *Nix builds, but left them in the Windows builds. Allow me to explain my reasoning:

1. libuv.dll is used by Kestrel, and is only needed when using OmniSharp is an HTTP server. When using OmniSharp with stdio, it isn't necessary at all.
2. libuv.dll is a platform-specific native dependency. So, it wouldn't be possible to include it in the omnisharp-mono package anyway.
3. It is mind-numbingly easy to install on *Nix (e.g. `brew install libuv` or `sudo apt-get install libuv1`). It is not as easy to acquire on Windows however.

I'm open to discussion on this decision.

### CODE REVIEW

**Comment by mholo65** [comment]
@DustinCampbell will you not support .NET Core in the future? Is it Full Framework or nothing?

**Comment by DustinCampbell** [comment]
@mholo65:

> will you not support .NET Core in the future? Is it Full Framework or nothing?

There two aspects here:

1. What runtime OmniSharp itself runs on.
2. What sorts of projects OmniSharp can handle

This PR is only about the first point above. OmniSharp will no longer provide stand-alone builds that run on .NET Core. Primarily, this is because those builds are limited in what sorts of projects they can process. (i.e. MSBuild tasks targeting Full Framework will likely not run on CoreCLR). For OSX/Linux, we're going to be bundling a local Mono runtime so that OmniSharp will still run as a standalone application, without requiring Mono to be installed on the system (see #666 for details).

The second point above is not changing at all. OmniSharp will continue to support processing both .NET Core and Full Framework projects.

Does that answer your question?

**Comment by DustinCampbell** [comment]
Note that this will just be formalizing what we already do in C# for VS Code to run OmniSharp.

**Comment by mholo65** [comment]
@DustinCampbell yes! Thanks, this is good news for us in Cake team, now we only need to target full framework for the Cake-plugin!

**Comment by DustinCampbell** [comment]
OK. Builds are passing. Tests are still somewhat problematic but they're working at the moment. Next up: packaging.

**Comment by DustinCampbell** [comment]
@david-driscoll & @filipw: I added you two in case you want to start looking at this or would like to try the branch out.

**Comment by DustinCampbell** [comment]
Note: This change does *not* move our libraries over to netstandard2.0. I think that's possibly the next thing, but it's not needed yet.

**Comment by filipw** [comment]
We also have some conditional compilation directives which could be dropped now i.e. [here](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.MSBuild/MSBuildEnvironment.cs#L150) or [here](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Host/Services/AssemblyLoader.cs#L69)

**Comment by DustinCampbell** [comment]
OK. I'm starting over a bit. I've rebased onto master with the new updates to the build.

**Comment by mholo65** [comment]
@DustinCampbell any plans on updating target framework for `OmniSharp.exe` to `net462` or `net47`? Or will this be done once `netstandard2.0` is released? We are updating target frameworks for `Cake` in the next version and want to make sure Cake support (https://github.com/OmniSharp/omnisharp-roslyn/pull/932/) still works as we need to load `Cake.Core` into OmniSharp in order to get the `hostObjectType` for scripting (https://github.com/OmniSharp/omnisharp-roslyn/pull/932/files#diff-3f2a987ebd93be29eeb71b6f6d923decR151)

**Comment by DustinCampbell** [comment]
No plans yet. Keeping the target framework it at 4.6 means that it will work on more Windows versions without the user needing to do anything.

**Comment by eamodio** [comment]
@DustinCampbell does this mean we won't be able to debug omnisharp on macOS/Linux (via vscode)?

**Comment by DustinCampbell** [comment]
I would expect the Mono Debugger extension to work, though I've never tried it.

**Comment by DustinCampbell** [comment]
> Do we have a plan to handle new mono versions, some repo or script we can setup to manage that?

Not yet. We're just using the bits that I regularly cobble together for C# for VS Code. I have a script that I use to copy the bits out of an installation of Mono on OSX. However, for Linux x86/x64, I have VMs where I sudo apt-get the latest mono and copy the runtimes out.

**Comment by DustinCampbell** [comment]
Are you guys OK if I merge this? It's a big change, so I want to be sure.

**Comment by filipw** [comment]
absolutely, I can't wait to get rid of .NET Core 😃🏆🍻

**Comment by DustinCampbell** [comment]
OK. Here it goes. :smile:

**Comment by danmosemsft** [comment]
@joperezr

**Pull request merged**
