### PR TITLE
Load analyzers from .csproj without restart

### PR DESCRIPTION
**Pull request by savpek**
This PR support analyzer references to update without full restart (restore required). Previously any change for analyzer references in csproj reguired full restart of omnisharp-roslyn.

This is waiting for #1440 to be merged since i want to use parts of it's existing test code with this one.

### CODE REVIEW

**Comment by david-driscoll** [comment]
@savpek is this one ready now the other PR is merged?

**Comment by savpek** [comment]
@david-driscoll i will write few tests in top of test project added in another PR merge. After that them this is ready. I think i can do them in few days in time.

**Comment by savpek** [comment]
@david-driscoll ready for review

**Comment by savpek** [comment]
and for @filipw @rchande @mholo65 too ofc ready for review.

**Pull request merged**
