### PR TITLE
Support solution filters (*.slnf)

### PR DESCRIPTION
**Pull request by sharwell**
Addresses https://github.com/dotnet/roslyn/pull/47531#pullrequestreview-485152426

I'm not sure how to test this.

### CODE REVIEW

**Comment by filipw** [comment]
you can add a new test-asset representing slnf and add a similar test to this https://github.com/OmniSharp/omnisharp-roslyn/blob/433dd1757a1199c48fb82964074fc0640e09d1f4/tests/OmniSharp.MSBuild.Tests/WorkspaceInformationTests.cs#L23-L48 to ensure OmniSharp loads it correctly

**Comment by 333fred** [comment]
Hmm @sharwell that new test failure is the same one that I observed locally, that went away on re-run :/

**Review by JoeRobich — APPROVED** [review]

**Comment by filipw** [comment]
superseded by https://github.com/OmniSharp/omnisharp-roslyn/pull/2121

**Comment by sharwell** [comment]
@filipw works for me thanks!

**Pull request closed without merging**
