### PR TITLE
Trigger completion on space if object creation completion is available

### PR DESCRIPTION
**Pull request by rchande**
...if object creation completion is available. Currently does not
attempt to implement any preselection-like experience.

Depends on https://github.com/OmniSharp/omnisharp-vscode/pull/1776

### CODE REVIEW

**Comment by rchande** [comment]
Tag @DustinCampbell -- for some reason the "reviewers" UI won't let me add you that way.

**Comment by DustinCampbell** [comment]
> Tag @DustinCampbell -- for some reason the "reviewers" UI won't let me add you that way.

You're only officially a member of the omnisharp-vscode team.

**Comment by rchande** [comment]
@DustinCampbell What's left in #884? Is it something I could help finish up for you?

**Comment by rchande** [comment]
Also cc @piotrpMSFT and @jonsequitur in case they're interested.

**Comment by DustinCampbell** [comment]
There's not much left in #884. I ran into some workspace issues where tracking document open/close states became necessary due to a bug in Roslyn's AbstractMemberInsertingCompletionProvider [that I fixed here](https://github.com/dotnet/roslyn/pull/20108). I got side-tracked while making the open/close states work though.

**Comment by david-driscoll** [comment]
Kicked travis... the mac build failed for some reason.

**Pull request merged**
