### PR TITLE
Exclude additive classifications from "/highlight" requests

### LINKED ISSUE #1576: Inconsistent /highlight Kinds
When using the `/highlight` endpoint, the "Kind" included in the response is inconsistent. Here are some screenshots to demonstrate - each has only a single "Kind" coloured:

`static symbol`
screenshot-highlight-static-symbol

`class name`
screenshot-highlight-class-name

`method name`
screenshot-highlight-method-name

<details>
<summary>
Expand: The full response for the `/highlight` request
</summary>

```json
{
   "Request_seq": 1003,
   "Command": "/highlight",
   "Running": true,
   "Success": true,
   "Message": null,
   "Body": {
      "Highlights": [
         {
            "StartLine": 1,
            "StartColumn": 1,
            "EndLine": 1,
            "EndColumn": 6,
            "Kind": "keyword",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 1,
            "StartColumn": 7,
            "EndLine": 1,
            "EndColumn": 13,
            "Kind": "namespace name",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 1,
            "StartColumn": 13,
            "EndLine": 1,
            "EndColumn": 14,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 3,
            "StartColumn": 1,
            "EndLine": 3,
            "EndColumn": 10,
            "Kind": "keyword",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 3,
            "StartColumn": 11,
            "EndLine": 3,
            "EndColumn": 16,
            "Kind": "namespace name",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 4,
            "StartColumn": 1,
            "EndLine": 4,
            "EndColumn": 2,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 5,
            "StartColumn": 5,
            "EndLine": 5,
            "EndColumn": 10,
            "Kind": "keyword",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 5,
            "StartColumn": 11,
            "EndLine": 5,
            "EndColumn": 18,
            "Kind": "class name",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 6,
            "StartColumn": 5,
            "EndLine": 6,
            "EndColumn": 6,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 7,
            "StartColumn": 9,
            "EndLine": 7,
            "EndColumn": 15,
            "Kind": "keyword",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 7,
            "StartColumn": 16,
            "EndLine": 7,
            "EndColumn": 20,
            "Kind": "keyword",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 7,
            "StartColumn": 21,
            "EndLine": 7,
            "EndColumn": 25,
            "Kind": "static symbol",
            "Projects": [
               "Hello",
               "Hello"
            ]
         },
         {
            "StartLine": 7,
            "StartColumn": 25,
            "EndLine": 7,
            "EndColumn": 26,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 7,
            "StartColumn": 26,
            "EndLine": 7,
            "EndColumn": 32,
            "Kind": "keyword",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 7,
            "StartColumn": 32,
            "EndLine": 7,
            "EndColumn": 33,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 7,
            "StartColumn": 33,
            "EndLine": 7,
            "EndColumn": 34,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 7,
            "StartColumn": 35,
            "EndLine": 7,
            "EndColumn": 39,
            "Kind": "parameter name",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 7,
            "StartColumn": 39,
            "EndLine": 7,
            "EndColumn": 40,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 8,
            "StartColumn": 9,
            "EndLine": 8,
            "EndColumn": 10,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 9,
            "StartColumn": 13,
            "EndLine": 9,
            "EndColumn": 20,
            "Kind": "static symbol",
            "Projects": [
               "Hello",
               "Hello"
            ]
         },
         {
            "StartLine": 9,
            "StartColumn": 20,
            "EndLine": 9,
            "EndColumn": 21,
            "Kind": "operator",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 9,
            "StartColumn": 21,
            "EndLine": 9,
            "EndColumn": 30,
            "Kind": "static symbol",
            "Projects": [
               "Hello",
               "Hello"
            ]
         },
         {
            "StartLine": 9,
            "StartColumn": 30,
            "EndLine": 9,
            "EndColumn": 31,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 9,
            "StartColumn": 31,
            "EndLine": 9,
            "EndColumn": 45,
            "Kind": "string",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 9,
            "StartColumn": 45,
            "EndLine": 9,
            "EndColumn": 46,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 9,
            "StartColumn": 46,
            "EndLine": 9,
            "EndColumn": 47,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 10,
            "StartColumn": 13,
            "EndLine": 10,
            "EndColumn": 20,
            "Kind": "class name",
            "Projects": [
               "Hello",
               "Hello"
            ]
         },
         {
            "StartLine": 10,
            "StartColumn": 20,
            "EndLine": 10,
            "EndColumn": 21,
            "Kind": "operator",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 10,
            "StartColumn": 21,
            "EndLine": 10,
            "EndColumn": 30,
            "Kind": "method name",
            "Projects": [
               "Hello",
               "Hello"
            ]
         },
         {
            "StartLine": 10,
            "StartColumn": 30,
            "EndLine": 10,
            "EndColumn": 31,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 10,
            "StartColumn": 31,
            "EndLine": 10,
            "EndColumn": 45,
            "Kind": "string",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 10,
            "StartColumn": 45,
            "EndLine": 10,
            "EndColumn": 46,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 10,
            "StartColumn": 46,
            "EndLine": 10,
            "EndColumn": 47,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 11,
            "StartColumn": 13,
            "EndLine": 11,
            "EndColumn": 20,
            "Kind": "class name",
            "Projects": [
               "Hello",
               "Hello"
            ]
         },
         {
            "StartLine": 11,
            "StartColumn": 20,
            "EndLine": 11,
            "EndColumn": 21,
            "Kind": "operator",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 11,
            "StartColumn": 21,
            "EndLine": 11,
            "EndColumn": 30,
            "Kind": "static symbol",
            "Projects": [
               "Hello",
               "Hello"
            ]
         },
         {
            "StartLine": 11,
            "StartColumn": 30,
            "EndLine": 11,
            "EndColumn": 31,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 11,
            "StartColumn": 31,
            "EndLine": 11,
            "EndColumn": 45,
            "Kind": "string",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 11,
            "StartColumn": 45,
            "EndLine": 11,
            "EndColumn": 46,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 11,
            "StartColumn": 46,
            "EndLine": 11,
            "EndColumn": 47,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 12,
            "StartColumn": 13,
            "EndLine": 12,
            "EndColumn": 20,
            "Kind": "class name",
            "Projects": [
               "Hello",
               "Hello"
            ]
         },
         {
            "StartLine": 12,
            "StartColumn": 20,
            "EndLine": 12,
            "EndColumn": 21,
            "Kind": "operator",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 12,
            "StartColumn": 21,
            "EndLine": 12,
            "EndColumn": 30,
            "Kind": "method name",
            "Projects": [
               "Hello",
               "Hello"
            ]
         },
         {
            "StartLine": 12,
            "StartColumn": 30,
            "EndLine": 12,
            "EndColumn": 31,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 12,
            "StartColumn": 31,
            "EndLine": 12,
            "EndColumn": 45,
            "Kind": "string",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 12,
            "StartColumn": 45,
            "EndLine": 12,
            "EndColumn": 46,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 12,
            "StartColumn": 46,
            "EndLine": 12,
            "EndColumn": 47,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 13,
            "StartColumn": 13,
            "EndLine": 13,
            "EndColumn": 20,
            "Kind": "static symbol",
            "Projects": [
               "Hello",
               "Hello"
            ]
         },
         {
            "StartLine": 13,
            "StartColumn": 20,
            "EndLine": 13,
            "EndColumn": 21,
            "Kind": "operator",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 13,
            "StartColumn": 21,
            "EndLine": 13,
            "EndColumn": 30,
            "Kind": "method name",
            "Projects": [
               "Hello",
               "Hello"
            ]
         },
         {
            "StartLine": 13,
            "StartColumn": 30,
            "EndLine": 13,
            "EndColumn": 31,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 13,
            "StartColumn": 31,
            "EndLine": 13,
            "EndColumn": 45,
            "Kind": "string",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 13,
            "StartColumn": 45,
            "EndLine": 13,
            "EndColumn": 46,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 13,
            "StartColumn": 46,
            "EndLine": 13,
            "EndColumn": 47,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 14,
            "StartColumn": 13,
            "EndLine": 14,
            "EndColumn": 20,
            "Kind": "class name",
            "Projects": [
               "Hello",
               "Hello"
            ]
         },
         {
            "StartLine": 14,
            "StartColumn": 20,
            "EndLine": 14,
            "EndColumn": 21,
            "Kind": "operator",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 14,
            "StartColumn": 21,
            "EndLine": 14,
            "EndColumn": 30,
            "Kind": "static symbol",
            "Projects": [
               "Hello",
               "Hello"
            ]
         },
         {
            "StartLine": 14,
            "StartColumn": 30,
            "EndLine": 14,
            "EndColumn": 31,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 14,
            "StartColumn": 31,
            "EndLine": 14,
            "EndColumn": 45,
            "Kind": "string",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 14,
            "StartColumn": 45,
            "EndLine": 14,
            "EndColumn": 46,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 14,
            "StartColumn": 46,
            "EndLine": 14,
            "EndColumn": 47,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 15,
            "StartColumn": 13,
            "EndLine": 15,
            "EndColumn": 20,
            "Kind": "class name",
            "Projects": [
               "Hello",
               "Hello"
            ]
         },
         {
            "StartLine": 15,
            "StartColumn": 20,
            "EndLine": 15,
            "EndColumn": 21,
            "Kind": "operator",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 15,
            "StartColumn": 21,
            "EndLine": 15,
            "EndColumn": 30,
            "Kind": "method name",
            "Projects": [
               "Hello",
               "Hello"
            ]
         },
         {
            "StartLine": 15,
            "StartColumn": 30,
            "EndLine": 15,
            "EndColumn": 31,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 15,
            "StartColumn": 31,
            "EndLine": 15,
            "EndColumn": 45,
            "Kind": "string",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 15,
            "StartColumn": 45,
            "EndLine": 15,
            "EndColumn": 46,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 15,
            "StartColumn": 46,
            "EndLine": 15,
            "EndColumn": 47,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 16,
            "StartColumn": 13,
            "EndLine": 16,
            "EndColumn": 20,
            "Kind": "class name",
            "Projects": [
               "Hello",
               "Hello"
            ]
         },
         {
            "StartLine": 16,
            "StartColumn": 20,
            "EndLine": 16,
            "EndColumn": 21,
            "Kind": "operator",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 16,
            "StartColumn": 21,
            "EndLine": 16,
            "EndColumn": 30,
            "Kind": "method name",
            "Projects": [
               "Hello",
               "Hello"
            ]
         },
         {
            "StartLine": 16,
            "StartColumn": 30,
            "EndLine": 16,
            "EndColumn": 31,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 16,
            "StartColumn": 31,
            "EndLine": 16,
            "EndColumn": 45,
            "Kind": "string",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 16,
            "StartColumn": 45,
            "EndLine": 16,
            "EndColumn": 46,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 16,
            "StartColumn": 46,
            "EndLine": 16,
            "EndColumn": 47,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 17,
            "StartColumn": 9,
            "EndLine": 17,
            "EndColumn": 10,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 18,
            "StartColumn": 5,
            "EndLine": 18,
            "EndColumn": 6,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         },
         {
            "StartLine": 19,
            "StartColumn": 1,
            "EndLine": 19,
            "EndColumn": 2,
            "Kind": "punctuation",
            "Projects": [
               "Hello"
            ]
         }
      ]
   },
   "Seq": 34,
   "Type": "response"
}
```
</details>

### PR DESCRIPTION
**Pull request by DasCleverle**
Currently the behavior of the "/highlight" request is not deterministic for static symbols. This is because the Classifier class returns two ClassifiedSpans for static symbols (one with the actual kind and one with kind "static symbol"). And depending on which of the two spans is returned first in the result we get a different highlight span.

I propose a change where we remove these "additive" kinds from the result, only returning the actual kind of the span.

Fixes #1576

### CODE REVIEW

**Comment by nickspoons** [comment]
I can confirm that this PR fixes #1576, thanks @DasCleverle!

I'm not sure if it is related but I notice that `WriteLine` has kind `method name` when it is contains anything valid but has kind `identifier` when it contains e.g. an undeclared variable:

```csharp
Console.WriteLine("a string");
Console.WriteLine(5);
object o = "another string";
Console.WriteLine(o.ToString());
Console.WriteLine(undeclared_variable.ToString());
```

image

Is this another situation where there are multiple spans?

**Comment by DasCleverle** [comment]
No, it seems that Roslyn can't determine the actual kind when there is a semantic error. This is what I got for the sample you provided:

image

**Comment by nickspoons** [comment]
I don't think the CI errors have anything to do with the PR - can someone trigger them for a rebuild?

**Comment by DasOhmoff** [comment]
Thank you all very much for fixing this issue. It is very appreciated <3

**Pull request merged**
