### PR TITLE
Enable OmniSharp.Cake tests for .NET 6

### PR DESCRIPTION
**Pull request by bjorkstromm**

### CODE REVIEW

**Review by JoeRobich — APPROVED** [review]
🎉

**Comment by filipw** [comment]
looks like some of the tests deadlocked (?)

**Comment by JoeRobich** [comment]
This error in the failing MacOS leg looks suspicious.
```
[fail]: OmniSharp.WorkspaceInitializer
         The project system 'OmniSharp.Cake.CakeProjectSystem' threw exception during initialization.
 System.ComponentModel.Win32Exception (8): An error occurred trying to start process '/Users/runner/work/omnisharp-roslyn/omnisharp-roslyn/test-assets/test-projects/CakeProject/tools/Cake.Bakery.0.9.0/tools/Cake.Bakery.exe' with working directory '/Users/runner/work/omnisharp-roslyn/omnisharp-roslyn/test-assets/test-projects/CakeProject'. Exec format error
 ```

**Comment by bjorkstromm** [comment]
> This error in the failing MacOS leg looks suspicious.
> ```
> [fail]: OmniSharp.WorkspaceInitializer
>          The project system 'OmniSharp.Cake.CakeProjectSystem' threw exception during initialization.
>  System.ComponentModel.Win32Exception (8): An error occurred trying to start process '/Users/runner/work/omnisharp-roslyn/omnisharp-roslyn/test-assets/test-projects/CakeProject/tools/Cake.Bakery.0.9.0/tools/Cake.Bakery.exe' with working directory '/Users/runner/work/omnisharp-roslyn/omnisharp-roslyn/test-assets/test-projects/CakeProject'. Exec format error
>  ```

Hmm, we don't have Mono at all in the .NET 6 tests I assume. Cake.Bakery itself is a .NET 6 console app, but it includes a wrapper for Mono. I'll add a check if we are running Mono or .NET6 and launch the appropriate executable based on runtime.

**Review by 333fred — APPROVED** [review]

**Comment by filipw** [comment]
I merged this, although I hope this deadlock is now really gone and not that the checks just passed 'accidentally' 😅

**Pull request merged**
