### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by DustinCampbell**
Loads of refactoring and clean up in unit tests. New concepts:

* `TestContent`: This unifies the process of marking up test code with a caret position or spans. It is similar to [`MarkupTestFile`](https://github.com/dotnet/roslyn/blob/master/src/Test/Utilities/Shared/MarkedSource/MarkupTestFile.cs) from Roslyn. The idea is that we should have a single way to specify this information in tests.
* `TestFile`: Couples `TestContent` with a file name. Rather than passing around dictionaries of string -> string, tests now pass around arrays of TestFile.
* `TextPoint` and `TextRange`: These are simple structs for handle line/offset pairs. Note that these do not use the term "Column", which is usually reserved in editors to represent a position within a line after tabs are expanded.

Also, found a few bugs and fixed 'em.

### CODE REVIEW

**Comment by filipw** [comment]
> Rather than passing around dictionaries of string -> string, tests now pass around arrays of TestFile.

I swear, it somehow felt like a good idea at a time 😊

**Comment by DustinCampbell** [comment]
@david-driscoll, how does this look to you?

**Comment by filipw** [comment]
:shipit:

**Comment by DustinCampbell** [comment]
Ping @david-driscoll

**Comment by DustinCampbell** [comment]
Thanks!

**Pull request merged**
