### PR TITLE
Fixes msbuild loading when LangVersion is missing

### PR DESCRIPTION
**Pull request by nosami**
Fixes https://github.com/OmniSharp/omnisharp-atom/issues/325

### CODE REVIEW

**Comment by nosami** [comment]
Anyone know how to fix the build? `Unable to locate Nuget.Core >= 2.8.5. Do you mean NuGet.Core? ` https://ci.appveyor.com/project/nosami/omnisharp-roslyn-ufjxv/build/1.0.320#L1449

**Comment by nosami** [comment]
p.s. This is a critical bug ;)

**Comment by filipw** [comment]
isn't this just a nuget glitch when appveyor ran? on Travis it restored it correctly, also works locally for me

**Comment by filipw** [comment]
a lot of red here today http://status.nuget.org

**Comment by nosami** [comment]
Seems to be a Windows only issue. But on Travis, we have other problems.

I want to merge this regardless of any CI issues.

**Comment by nosami** [comment]
It's not really a glitch. Looks like the package was renamed by uppercasing the 'G'. See here https://github.com/OmniSharp/omnisharp-node-client#windows-developers

**Comment by filipw** [comment]
ugh ok I know how to fix it, change `"ScriptCs.Hosting.KpmTemp": "0.14.1"` in project.json to `"ScriptCs.Hosting": "0.14.1"`

before, they actually renamed it the opposite way (!) - from uppercase to lowercase, that's why we used that "temp" package in the first place :smile:

**Comment by nosami** [comment]
Oh wow. I wouldn't have figured that out!

**Comment by filipw** [comment]
after this change works on windows for me

screenshot 2015-05-22 10 57 37

**Comment by nosami** [comment]
Hurray! Build passed! I'm gonna break my own rule and merge this seeing as it's a trivial fix. 

If anyone want's me to change it, let me know :)

**Pull request merged**
