### PR TITLE
Fix span used to determine whether signature help should be shown

### PR DESCRIPTION
**Pull request by DustinCampbell**
OmniSharp used the full span of an argument list to determine whether signature help should be shown. However, that includes both leading and trailing trivia, which means that it would return signatures for positions outside of the argument list. In addition, I switched it to use `Contains(...)` rather than `IntersectsWith(...)` since checking the position against the argument list span should not include the outer positions (e.g. on the left or right of the parentheses).

This fixes https://github.com/OmniSharp/omnisharp-vscode/issues/64.

cc @david-driscoll, @troydai

### CODE REVIEW

**Comment by troydai** [comment]
:shipit:

**Comment by troydai** [comment]
I'll rebase it for ya.

**Comment by troydai** [comment]
Need rebase on latest dev. Travis build failures are fixed recently.

**Comment by DustinCampbell** [comment]
rebased

**Comment by DustinCampbell** [comment]
Cool. Passes now. Anyone else want to take a look?

**Comment by DustinCampbell** [comment]
@david-driscoll?

**Comment by filipw** [comment]
```
This branch is out-of-date with the base branch
Merge the latest changes from dev into this branch
```

**Comment by DustinCampbell** [comment]
@filipw  -- huh? I totally just rebased against dev

**Comment by DustinCampbell** [comment]
Trying again

**Comment by david-driscoll** [comment]
@DustinCampbell that was me... I merge something else, but it shouldn't have been a conflict.  Sorry. :sheep:

**Comment by DustinCampbell** [comment]
no worries. It really wasn't a conflict. :smile:

**Comment by david-driscoll** [comment]
No github is just a little more aggressive with it's merge policy.

**Comment by filipw** [comment]
great :+1:

**Pull request merged**
