### PR TITLE
Upgrade roslyn to 4.6.0-2.23128.12

### PR DESCRIPTION
**Pull request by dibarbet**

### CODE REVIEW

**Review by filipw — APPROVED** [review]
thank you!

**Comment by filipw** [comment]
@dibarbet the test failures look legit:

> Failed OmniSharp.Roslyn.CSharp.Tests.CompletionFacts.UsingsAddedInOrder(filename: "dummy.cs", useAsyncCompletion: False) [520 ms]
[35375](https://github.com/OmniSharp/omnisharp-roslyn/actions/runs/4318842426/jobs/7537616048#step:8:35376)
  Error Message:
[35376](https://github.com/OmniSharp/omnisharp-roslyn/actions/runs/4318842426/jobs/7537616048#step:8:35377)
   System.MissingMethodException : Method not found: 'Void Microsoft.CodeAnalysis.Completion.CompletionOptions.set_ShowItemsFromUnimportedNamespaces(System.Nullable`1<Boolean>)'.
[35377](https://github.com/OmniSharp/omnisharp-roslyn/actions/runs/4318842426/jobs/7537616048#step:8:35378)
  Stack Trace:
[35378](https://github.com/OmniSharp/omnisharp-roslyn/actions/runs/4318842426/jobs/7537616048#step:8:35379)
     at Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.Completion.OmniSharpCompletionOptions.ToCompletionOptions()

**Comment by dibarbet** [comment]
@filipw they are indeed.  Trying to fix them in https://github.com/dotnet/roslyn/pull/67163

**Comment by filipw** [comment]
nice, thank you!

**Pull request merged**
