### PR TITLE
Refinement of archive generation

### PR DESCRIPTION
**Pull request by hal-ler**
Proposal for simpler archiving logic. I'm also including existing functionality to make the behavior clear and easy to discuss.

Windows: nothing changes, archives generated with the `win-x64-{framework}` and `win-x86-{framework}` (for non-Local builds) identifiers.

Linux/Users: nothing changes, archives generated with the `linux-64-{framework}` identifiers for the local runtime.

Linux/Travis:
  - archive generated with the `mono` identifier for the local runtime using .NET 4.5.1 as framework.
  - archives generated with the `{osshortname}-x64` identifier for all the runtimes explicitly mentioned in PopulateRuntimes (none for the local one, we expect it to be in the list) using .NET Core as framework.

OSX/User: nothing changes, archive generated with the `osx-x64-{framework}` identifier for the local runtime.

OSX/Travis: nothing changes, archive generated with the `osx-x64` identifier for the local runtime using .NET Core as framework.

The differences are:
  - `linux-mono` -> `mono` to clarify that it works on OSX.
  - No more double archiving for local runtime and explicit Ubuntu. Safeguard to ignore OS variant on Travis/Linux. Users still get archive if they desire, using generic `linux-x64-{framework}` name.
  - No more `linux` alias for .NET Core.

Suggestions? Opinions?

@DustinCampbell @david-driscoll @troydai

### CODE REVIEW

**Comment by hal-ler** [comment]
Used wrong branch sorry.

**Comment by hal-ler** [comment]
Used wrong branch initially, sorry.

**Comment by david-driscoll** [comment]
`linux-mono` -> `mono` is breaking, but that's minor, and it's something I can get behind.

Everything else makes sense to me.

**Comment by hal-ler** [comment]
One question is if the OS versions should be kept for the Linux builds. The Ubuntu 16.04 binary might be incompatible with Ubuntu 14.04. It could lead to another set of breaking changes in the future.

**Comment by troydai** [comment]
os version should be in the builds' names. it is likely the implementation for os platforms will be various.

**Comment by david-driscoll** [comment]
I think we're fine without the os version for the moment, mainly because I don't see any specific ubuntu packages for cli either.

When they react with multiple versions per OS, I think that's the time we should as well.  Either way we can do that as part of another PR.

**Pull request merged**
