### PR TITLE
Fix master!

### PR DESCRIPTION
**Pull request by david-driscoll**

### CODE REVIEW

**Comment by DustinCampbell** [comment]
@david-driscoll: What's the plan for this PR?

**Comment by DustinCampbell** [comment]
I'm curious because every merge takes more time because this PR consumes a builds from Travis and AppVeyor with each merge.

**Comment by david-driscoll** [comment]
Good question... I'll close for now and reopen if we need it later (I know we want to move back to just a master branch not master/dev in the future anyway)

**Comment by DustinCampbell** [comment]
Thanks! These days, we kind of treat "dev" like "master".

**Pull request closed without merging**
