### PR TITLE
Adding .vscode/settings.json into .gitignore

### PR DESCRIPTION
**Pull request by dopare**
Just added `.vscode` folder into ignore list.

### CODE REVIEW

**Comment by david-driscoll** [comment]
I'm fine with leaving the folder in, I'm sure eventually we'll have some perfectly valid vscode tasks when developing with omnisharp. It's fine to keep it that way locally if you want, but I'm not certain we will always need to ignore it.  cc @DustinCampbell @troydai

**Comment by DustinCampbell** [comment]
If we have specific needs for OmniSharp in the launch.json, I think we'd want to check it in. If we don't, it shouldn't be a big deal to ignore these.

**Comment by dopare** [comment]
Sorry, I haven't thought about shared use of `launch.json` .

I am using latest `omnisharp-roslyn` build in VS code for `omnisharp-rolsyn` development via `settings.json`.
What do you think about ignoring just the `settings.json` ?

**Comment by troydai** [comment]
I think ignore `settings.json` makes more senses. Personalized setting can be saved in user setting instead of workspace setting.

**Comment by dopare** [comment]
Made changes to ignore only `settings.json`.

**Comment by DustinCampbell** [comment]
That sounds like the right fix to me. :+1:

**Comment by troydai** [comment]
:shipit:

**Comment by troydai** [comment]
The shadow copy issue happens more frequently now.

**Comment by troydai** [comment]
Thanks for the contribution, @dopare.

**Comment by dopare** [comment]
@troydai Thank you so much, it's my first step in open source.

**Comment by troydai** [comment]
Cheers!

**Pull request merged**
