### PR TITLE
Updated release date of 1.34.7 to today

### PR DESCRIPTION
**Pull request by JoeRobich**

### CODE REVIEW

**Comment by nickspoons** [comment]
No assets in [releases](https://github.com/OmniSharp/omnisharp-roslyn/releases) after over an hour ... did something in the Azure pipeline break?

**Comment by JoeRobich** [comment]
@nickspoons Thanks for letting me know. I'll look into it.

**Comment by filipw** [comment]
there was a - what appears to be - transient failure on the windows build. I restarted it

**Comment by nickspoons** [comment]
They're up now, cheers guys

**Pull request merged**
