### PR TITLE
add support for new .net core csproj guid in .sln files.

### PR DESCRIPTION
**Pull request by danwalmsley**

### CODE REVIEW

**Comment by danwalmsley** [comment]
I have tested this now and can confirm this fixes compatibility issue with new csproj guids.

**Comment by willl** [comment]
@danwalmsley But it has a dependency on the upgraded MS Build from @DustinCampbell's branch, right?

**Comment by DustinCampbell** [comment]
Yep. @danwalmsley: You should probably rebase and resubmit for the new-msbuild branch.

**Comment by DustinCampbell** [comment]
I went ahead and rebased this on the new-msbuild branch.

**Comment by DustinCampbell** [comment]
Thanks for the PR @danwalmsley! Sorry it took so long to get merged.

**Pull request merged**
