### PR TITLE
added FromBody to /projects action

### PR DESCRIPTION
**Pull request by Yantrio**
How do people want to start e2e testing? Do we ask people to make sure that this actually works via postman/an editor, this should've been caught pre PR-merge :(

### CODE REVIEW

**Comment by cubitouch** [comment]
This wasn't working with Postman (before creating test case) so I removed it, sorry about that.
If you have a way to test this using Postman (or anything else) I'm interrested.

**Comment by nosami** [comment]
@cubitouch it would _only_ work in Postman with a POST request when the [FromBody] attribute is present.

**Comment by cubitouch** [comment]
I did, not sure what was not ok... will retry next time :)

**Comment by nosami** [comment]
@Yantrio I don't think we need end to end tests yet. We can just test for the [FromBody] attribute (yuk!) being present on all POST actions?

**Comment by jchannon** [comment]
I'm still having issues with this endpoint even after this fix :(

**Pull request merged**
