### PR TITLE
Update versions to match .NET SDK 6 RC1

### PR DESCRIPTION
**Pull request by nohwnd**

### CODE REVIEW

**Comment by filipw** [comment]
These test failures look like a real issue - because it fails when loading projects with 5.0.302 SDK

```
   [fail]: OmniSharp.MSBuild.ProjectLoader
1456
                The "GetReferenceNearestTargetFrameworkTask" task failed unexpectedly.
1457
                System.MissingMethodException: Method not found: 'NuGet.Frameworks.NuGetFramework NuGet.Frameworks.NuGetFramework.ParseComponents(System.String, System.String)'.
1458
                   at NuGet.Build.Tasks.GetReferenceNearestTargetFrameworkTask.TryParseFramework(String targetFrameworkMoniker, String targetPlatformMoniker, String errorMessage, MSBuildLogger logger, NuGetFramework& nugetFramework)
1459
                   at NuGet.Build.Tasks.GetReferenceNearestTargetFrameworkTask.Execute()
1460
                   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1461
                   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()   [fail]: OmniSharp.MSBuild.ProjectLoader
1456
                The "GetReferenceNearestTargetFrameworkTask" task failed unexpectedly.
1457
                System.MissingMethodException: Method not found: 'NuGet.Frameworks.NuGetFramework NuGet.Frameworks.NuGetFramework.ParseComponents(System.String, System.String)'.
1458
                   at NuGet.Build.Tasks.GetReferenceNearestTargetFrameworkTask.TryParseFramework(String targetFrameworkMoniker, String targetPlatformMoniker, String errorMessage, MSBuildLogger logger, NuGetFramework& nugetFramework)
1459
                   at NuGet.Build.Tasks.GetReferenceNearestTargetFrameworkTask.Execute()
1460
                   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1461
                   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by nohwnd** [comment]
That overload for ParseComponents seems to be introduced here, so probably the NuGet.Frameworks assembly in that SDK does not have the change yet. 

https://github.com/NuGet/NuGet.Client/commit/935b1d2f5bef8d0d78a737190846b72f0bae30e9

What is the usual way to fix this? Adding dependency to this package for that assembly?

**Comment by nohwnd** [comment]
> What is the usual way to fix this? Adding dependency to this package for that assembly?

Tried that, it does not help.

**Comment by filipw** [comment]
@JoeRobich is the one person that knows how to navigate the muddy waters of Nuget DLLs 😀

**Comment by JoeRobich** [comment]
Closed as these changes were part of #2218

**Pull request closed without merging**
