### PR TITLE
Fix for - Lots of mscorlib issues with 3rd party packages #265

### PR DESCRIPTION
**Pull request by RevenantX**
Fixed according to comment at bug #265.

### CODE REVIEW

**Comment by nosami** [comment]
Thanks for doing this! Looks good. Are you missing a using statement though?

```
/home/travis/build/OmniSharp/omnisharp-roslyn/src/OmniSharp/MSBuild/MSBuildProjectSystem.cs(118,125): error CS0103: The name 'DesktopAssemblyIdentityComparer' does not exist in the current context
```

**Comment by RevenantX** [comment]
Hmm... "DesktopAssemblyIdentityComparer" in namespace - Microsoft.CodeAnalysis. On windows compiled without errors, but atom with omnisharp show error. Maybe this doesn't exists in used roslyn version?

**Comment by nosami** [comment]
Not sure. Same error on the Windows CI too - https://ci.appveyor.com/project/nosami/omnisharp-roslyn-ufjxv/build/1.0.691#L4484

**Comment by RevenantX** [comment]
Omnisharp shows dnxcore50 - https://i.gyazo.com/35fe26f7cd92457828b9359e19606741.png

**Comment by nosami** [comment]
ah... looks like it's going to need to be #ifdeffed out then for now

**Comment by RevenantX** [comment]
#if DNX5 ?

**Comment by nosami** [comment]
Sorry, should have mentioned. It's `#if DNX451`

**Comment by RevenantX** [comment]
Fixed.

**Comment by nosami** [comment]
Nice. I'll get this released

**Pull request merged**
