### PR TITLE
Upgraded to latest lsp

### PR DESCRIPTION
**Pull request by david-driscoll**
@mholo65 This upgrade went pretty well things seem to working..  I dunno if might help with your other issue.

### CODE REVIEW

**Comment by mholo65** [comment]
@david-driscoll I tried the alpha bits yesterday, with no success. Actually it didn’t even initialize using the C# LSP Client (version 0.12.1). Saw another exception too bubble up regarding converting ”empty json rpc response” to a ”initialized response”.. Or something like that. Can look again with this PR instead.

**Comment by mholo65** [comment]
Seeing this with C# LSP Client when updating Omnisharp to use LSP libs 0.13.0-alpha*

```
Finding descriptor for initialized
Starting: Routing Notification initialized
Converting params for Notification initialized to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializedParams
Failed to handle request initialized - System.ArgumentException: Object of type 'OmniSharp.Extensions.JsonRpc.EmptyRequest' cannot be converted to type 'OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializedParams'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.HandleNotification(IMediator mediator, IHandlerDescriptor handler, Object params, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteNotification>d__5.MoveNext()
```

Initialized params is empty, so don't know what happened here. https://microsoft.github.io/language-server-protocol/specification#initialized

Will look into this, and also try to fix the issues seen in #1505 and #1525 as these are not fixed yet with updating LSP libs.

**Comment by mholo65** [comment]
Fixes #1505
Fixes #1525

**Comment by vincentwoo** [comment]
Eagerly awaiting this merge! Was also running into the didChange handler failures.

**Comment by vincentwoo** [comment]
How's this coming along? Any blockers?

**Comment by sebasmonia** [comment]
Surprised this wasn't included in the last release :(

**Comment by filipw** [comment]
I chatted with @mholo65 yesterday and we updated the test from #1583 from Linux since it's unstable on Azure DevOps with the LSP changes in. We can investigate that separately next and it shouldn't hold up this PR, the test still runs on Mac and Windows for now.

Should be good to go now.

**Pull request merged**
