### PR TITLE
Updated lsp library to fix issue with signature help, etc

### PR DESCRIPTION
**Pull request by david-driscoll**
Fixes: #1887

### CODE REVIEW

**Comment by david-driscoll** [comment]
Tested locally and signature help is working as expected (and returning null when it should be!)

**Comment by david-driscoll** [comment]
Related PRs 
https://github.com/OmniSharp/csharp-language-server-protocol/pull/315
https://github.com/OmniSharp/csharp-language-server-protocol/pull/316

**Comment by david-driscoll** [comment]
looks like I might have some failing tests, let's see what I broke... :)

**Comment by WellspringCS** [comment]
kid hollering from the back seat...

"Are we there, yet?"

:smile:

**Comment by david-driscoll** [comment]
okay I'm stumped at the moment.

Using our embedded mono the tests stall (for what reason I can't really tell, it just gets "stuck").  With full mono it runs and passes no issues.

There have been some internal changes internal to the library however it gets more confusing because it works with netcoreapp2.1, netcoreapp3.1, net472 (windows), net472(full mono).

Anyone have any ideas what I might need to add to the embedded mono for things to work?  or magic commands I can run to help trace the issue? I've got everything setup in wsl2 and can replicate the issue that is in CI.

**Comment by filipw** [comment]
maybe you now have new types that are missing? https://github.com/OmniSharp/omnisharp-roslyn/blob/master/mono-packaging/copy-mono.sh#L91

**Pull request merged**
