### PR TITLE
Updated build tool version for NET 5 RC1

### PR DESCRIPTION
**Pull request by JoeRobich**

### CODE REVIEW

**Comment by filipw** [comment]
there is an RC1 already?!

**Comment by JoeRobich** [comment]
> there is an RC1 already?!

Almost, we are getting it ready to ship =)

**Review by filipw — APPROVED** [review]

**Comment by filipw** [comment]
is there another breaking change on msbuild minimum version? 😅

**Comment by JoeRobich** [comment]
> is there another breaking change on msbuild minimum version?

I can only handle one a year at most. =)

**Pull request merged**
