### PR TITLE
Update projects

### PR DESCRIPTION
**Pull request by troydai**
1. Update solution and xproj
2. Remove OmniSharp.Bootstrap and its tests
3. Update publish options

I'm removing `OmniSharp.Bootstrap` because it doesn't play a role currently. It also keep failing in VS. By removing it, we can save maintenance cost and CI time. @david-driscoll is refurbishing it in this PR: https://github.com/OmniSharp/omnisharp-roslyn/pull/496. We can add it back when the PR is accomplished.

### CODE REVIEW

**Comment by hal-ler** [comment]
LGTM

**Comment by troydai** [comment]
Thanks for lgtm.

**Comment by troydai** [comment]
I'll wait till @david-driscoll ack this. Since I'm removing `OmniSharp.Bootstrap` temporarily.

**Comment by david-driscoll** [comment]
We can nuke bootstrap, with the changes related to cli it's no longer needed.

**Pull request merged**
