### PR TITLE
Fix deployment

### PR DESCRIPTION
**Pull request by david-driscoll**

### CODE REVIEW

**Comment by david-driscoll** [comment]
This should fix the deployment issue we're seeing with releases :sheep:

**Comment by hal-ler** [comment]
Looks good, but I would also remove the win7-x86 for now, until that issue is fixed to avoid confusing people. Also does anyone have access to a RedHat box by any chance to double-check that the cross-compiled Linux binaries work properly?

**Comment by hal-ler** [comment]
LGTM

**Comment by david-driscoll** [comment]
:+1:

**Pull request merged**
