### PR TITLE
Move (back) over to MSBuild solution parsing API

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1580

This also adds initial tests for #863.

### CODE REVIEW

**Comment by filipw** [comment]
great - out of curiosity, what was the original reason for the custom parsing code?

**Comment by DustinCampbell** [comment]
There are a couple of things:

1. Before, we were using the "project type GUID" to detect Unity projects and such. But I've now handled that through other means. Checking for ".csproj" is good enough.

2. When I originally tried to use MSBuild's API, I tried to use the "AbsolutePath" property for each project and found that had a bug with non-Windows slashes. Sticking with the "RelativePath" found in the solution file and keeping our existing logic for converting slashes avoids that bug.

**Comment by filipw** [comment]
thanks

**Comment by DustinCampbell** [comment]
Thanks guys!

**Pull request merged**
