### PR TITLE
Update Roslyn version and tools to match .NET 5 Preview8

### PR DESCRIPTION
**Pull request by JoeRobich**
Not sure whether we would want the included build tools to match the .NET SDK tools or the latest VS preview tools.

### CODE REVIEW

**Comment by JoeRobich** [comment]
Versions taken from https://github.com/dotnet/sdk/blob/release/5.0.1xx-preview8/eng/Versions.props, although it can be a moving target.

**Comment by JoeRobich** [comment]
I will need to update the SDK to a published version.

**Comment by JoeRobich** [comment]
Going to revert changing the SDK we use in out tests. Will perform manual validation of this build with NET 5 preview. We can update the version after it is released instead of relying on a nightly.

**Comment by JoeRobich** [comment]
Had to revert to an earlier build of Roslyn. These tests caught a regression in `RuntimeMetadataReferenceResolver` on Mono platforms.

**Comment by filipw** [comment]
good test then 🥁

**Pull request merged**
