### PR TITLE
Cli.... YOLO!

### PR DESCRIPTION
**Pull request by david-driscoll**
(we hope)

### CODE REVIEW

**Comment by troydai** [comment]
I want to believe.

**Comment by troydai** [comment]
Passed.

**Comment by DustinCampbell** [comment]
missing my change from this morning?

**Comment by troydai** [comment]
ee17829169eac29422fa1d72f0befdb3c2cf7096? It's on it.

**Comment by troydai** [comment]
:shipit:

**Comment by filipw** [comment]
wooot :chicken:

**Pull request merged**
