### PR TITLE
Fix build on macOS Sierra

### LINKED ISSUE #643: Can't build on macOS Sierra
Hey,

Just tried to build `omnisharp` on macOS Sierra 10.12 and run into multiple errors. I saw similar issue on other projects and if I understand the problem correctly, this must be fixed on project level.

# Problem

```
$ git rev-parse HEAD
3d943b4f5b21ce97667a0be06b8110e63c6456ec

$ ./build.sh
Feeds used:
  /Users/d12frosted/.local/share/NuGet/Cache
  /Users/d12frosted/.nuget/packages/
  https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
  https://api.nuget.org/v3/index.json

All packages listed in /Users/d12frosted/Developer/Other/omnisharp-roslyn/scripts/packages.config are already installed.
Analyzing build script...
Processing build script...
Installing addins...
Compiling build script...

========================================
Cleanup
========================================
Executing task: Cleanup
Finished executing task: Cleanup

========================================
BuildEnvironment
========================================
Executing task: BuildEnvironment
dotnet-install: .NET SDK version 1.0.0-preview2-003121 is already installed.
dotnet-install: Adding to current process PATH: /Users/d12frosted/Developer/Other/omnisharp-roslyn/.dotnet. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished successfully.
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
Feeds used:
  https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
  https://api.nuget.org/v3/index.json

Package "xunit.runner.console.2.2.0-beta2-build3300" is already installed.
Finished executing task: BuildEnvironment

========================================
PopulateRuntimes
========================================
Executing task: PopulateRuntimes
Finished executing task: PopulateRuntimes

========================================
Setup
========================================
Executing task: Setup
Finished executing task: Setup

========================================
Restore
========================================
Executing task: Restore
Restoring packages....
Package restore successful!
Restoring packages....
log  : Restoring packages for /Users/d12frosted/Developer/Other/omnisharp-roslyn/tests/TestSamples/ProjectSearchSample06/src/Project2/project.json...
log  : Restoring packages for /Users/d12frosted/Developer/Other/omnisharp-roslyn/tests/TestSamples/ProjectSearchSample06/tests/Test1/project.json...
log  : Restoring packages for /Users/d12frosted/Developer/Other/omnisharp-roslyn/tests/TestUtility/project.json...
log  : Restoring packages for /Users/d12frosted/Developer/Other/omnisharp-roslyn/tests/TestSamples/ProjectSearchSample07/tests/Test1/project.json...
log  : Restoring packages for /Users/d12frosted/Developer/Other/omnisharp-roslyn/tests/TestSamples/ProjectSearchSample07/src/Project1/project.json...
log  : Restoring packages for /Users/d12frosted/Developer/Other/omnisharp-roslyn/tests/TestSamples/ProjectSearchSample07/src/Project2/project.json...
log  : Restoring packages for /Users/d12frosted/Developer/Other/omnisharp-roslyn/tests/TestSamples/ProjectSearchSample07/src/Project2/Embed/project.json...
log  : Restoring packages for /Users/d12frosted/Developer/Other/omnisharp-roslyn/tests/TestSamples/ProjectSearchSample06/src/Project2/Embed/project.json...
error: System.Diagnostics.Process 4.1.0 provides a compile-time reference assembly for System.Diagnostics.Process on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with osx.10.12-x64.

...
```

Full log can be found [here](https://github.com/OmniSharp/omnisharp-roslyn/files/487614/roslyn.txt).

Oh, and just to make this report more interesting, here is screenshot that made my day. I wasn't ready for this 💃 😸 

screenshot 2016-09-22 18 04 53

P. S. Sorry if it's actually not related to Omnisharp.

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #643

This should fix builds on macOS Sierra.

There were a couple of problems that needed fixing due to runtime packages not being available for macOS Sierra (osx.10.12-x64).

1. The build script specified `dotnet restore --infer-runtimes`. Since there aren't runtime packages for macOS Sierra, it failed. We actually don't to specify this any longer, so I removed the flag.
2. OmniSharp.Tests was defined in a way that was pretty broken and impacted the build in a nasty way. Essentially, it tries to be both a library (because it contains test helper code), and an app (because it contains tests). This change makes it strictly an app, which fixes "dotnet build". A future change will refactoring the test helper code out into a different library.
3. `dotnet publish` needs to specify a runtime on macOS Sierra. Otherwise, it will specify the current runtime (osx.10.12-x64), which doesn't exist. So, the build script now detects the current RID by looking at the output of `dotnet --info`. Then, in the publish step, the build script checks to see if the current RID is `osx.10.12-x64` when attempting to publish for "default" and uses `osx.10.11-x64` instead.

### CODE REVIEW

**Comment by DustinCampbell** [comment]
really? hmmm...

**Comment by DustinCampbell** [comment]
i think i see where it's failing.

**Comment by DustinCampbell** [comment]
@wjk: I'm installing Sierra now. Want to try again after my last tweak?

**Comment by DustinCampbell** [comment]
nevermind. this won't fix it yet.

The problem is that OmniSharp is using `dotnet restore --infer-runtimes` to run restore for unit tests. On macOS sierra, that means it'll try to restore for osx.10.12-x64, which won't work until there are new packages published that support that. I'll need to take a closer look at the build script to clean this up.

**Comment by DustinCampbell** [comment]
OK. Fingers crossed. Works on my (macOS Sierra) machine.

**Comment by DustinCampbell** [comment]
cc @david-driscoll

**Comment by DustinCampbell** [comment]
Note: Adding all of the runtimes to the test projects (+ an extra one for AppVeyor) feels just awful. Does anyone have any better ideas here?

**Comment by d12frosted** [comment]
Thanks, that fixes my issue! 😸 ❤️

**Pull request merged**
